### ISSUE TITLE
Screen icons 

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/density#10]
what do you think about these icons for the screens?
Intro
![image](https://user-images.githubusercontent.com/26031501/76810800-f1662980-67b4-11ea-9af1-3867de04bc19.png)

Compare
![image](https://user-images.githubusercontent.com/26031501/76810811-ff1baf00-67b4-11ea-9aee-8b1118538da4.png)

Mistery
![image](https://user-images.githubusercontent.com/26031501/76810823-08a51700-67b5-11ea-8032-644c0e0d2408.png)

**Comment by ariel-phet** [comment]
@DianaTavares they are a bit too similar, and generally we try not to put text on icons.

1. For the first icon, I would just have a single block, ideally the simplest texture

2. For compare, having two blocks seems reasonable, but maybe just take off the masses

3. For mystery, perhaps use the scale?

**Comment by DianaTavares** [comment]
The scale looks strange without 3D and I think that if one icon is 3D, then the others need to be as well.   What about this updated version: 

![image](https://user-images.githubusercontent.com/26031501/76819324-72311f80-67cd-11ea-83dc-3827bb4b8210.png)

**Comment by arouinfar** [comment]
> The scale looks strange without 3D and I think that if one icon is 3D, then the others need to be as well. 

@DianaTavares I think the icons can be simple enough for @jonathanolson to draw in code, so the perspective should not be an issue. 

I like your sketches of the Intro and Compare icons. 

For Mystery, I think it's nice to include the scale, since it's only found on that screen. I would not include the readout on the scale, but I would consider keeping the question mark on the mass. A good comparison would be Function Builder's Mystery screen:
<img src="https://user-images.githubusercontent.com/8419308/77016515-78460e00-693d-11ea-8be1-dec0323ed08f.png" width=200>

**Comment by DianaTavares** [comment]
Nice! then this is the update of the Mystery screen icon (I didn't delete the kg because I am not sure if without that is obvious that it is a scale):

![image](https://user-images.githubusercontent.com/26031501/77017310-c825d480-693f-11ea-925e-a206f20df932.png)

Then to have something like this:
![image](https://user-images.githubusercontent.com/26031501/77017634-906b5c80-6940-11ea-9fc3-a5288c6f5e20.png)

**Comment by ariel-phet** [comment]
@DianaTavares those look good, but I would recommend 2 changes:

1. take away the "kg" on the scale. I think it does not need to be there to convey the meaning of the icon.

2. For the "Compare" screen, move the two blocks horizonatally away from each other so there is more negative space between them. They look a bit strange being so close together (maybe half a block width between them would be good)

**Comment by DianaTavares** [comment]
ready!  I change the colors of the blocks because I feel that green can get more lost when is under the water that red. 

Let me know what is the next step now! 

![image](https://user-images.githubusercontent.com/26031501/77486233-c7d08200-6df4-11ea-9cbe-e7d74575475f.png)

**Comment by ariel-phet** [comment]
@DianaTavares looks good to me

**Comment by DianaTavares** [comment]
@jonathanolson, then these are the icons for the density sim. My 3D drawing in Illustrator is not the best, Can you do it in code? 
 
> ![image](https://user-images.githubusercontent.com/26031501/77486233-c7d08200-6df4-11ea-9cbe-e7d74575475f.png)

**Comment by jonathanolson** [comment]
Implemented initial versions of the icons, how do they look?

**Comment by arouinfar** [comment]
The icons are generally looking good to me @jonathanolson, but they are pretty aliased. I think that's acceptable for the prototype, but I would want things looking crisper for actual production.

![image](https://user-images.githubusercontent.com/8419308/77699345-e0b57080-6f77-11ea-920a-9e72b7136388.png)
![image](https://user-images.githubusercontent.com/8419308/77699356-e612bb00-6f77-11ea-8403-93f765719691.png)
![image](https://user-images.githubusercontent.com/8419308/77699367-ec089c00-6f77-11ea-9f68-bb2285116aa9.png)

**Comment by DianaTavares** [comment]
I agree with @arouinfar 
>  I would want things looking crisper for actual production.

**Comment by jonathanolson** [comment]
Should be fixed on master now, can you verify?

**Comment by DianaTavares** [comment]
I look very well, thanks!!
Closing the issue.
