### ISSUE TITLE
Placement of blocks inconsistent when switching between block modes

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/density#102]
**Test device**
MacBook Air (m1 chip)

**Operating System**
11.6

**Browser**
chrome

**Problem description**
On the intro screen, if you switch back and forth (without changing anything else) between 1 block and 2 blocks, the "B" block will appear under the "A" block the second time around. I don't think this affects UX, but I wanted to note the inconsistency. 

**Steps to reproduce**
1. Select the intro screen
2. Select 2 blocks mode (block "B" drops on block "A")
3. Select 1 block mode
4. Select 2 blocks mode (block "A" is on block "B")

**Visuals**
![blockplacement](https://user-images.githubusercontent.com/87318828/135911649-4cc0c554-5b80-4829-8cca-e0b3fbb28eba.gif)

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: Density
URL: https://bayes.colorado.edu/dev/phettest/density/density_en.html?ea&brand=phet
Version: 1.0.0-dev.18 (unbuilt)
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36
Language: en-US
Window: 1391x690
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by jonathanolson** [comment]
@arouinfar @DianaTavares thoughts on whether this is a problem? It's behaving as expected, we'd presumably change locations of blocks if we want something different.

**Comment by arouinfar** [comment]
@jonathanolson @DianaTavares I don't think this is a serious usability problem, though it is a bit annoying. If it's easy to do, we could change the default initial positions to something like this:
![image](https://user-images.githubusercontent.com/8419308/141160666-fc21dc05-bf29-4f06-a410-a6d04fec1a04.png)

**Comment by DianaTavares** [comment]
I like @arouinfar  suggestion!

**Comment by jonathanolson** [comment]
That looks like an equilibrium position for the wooden block (we should compute that and precisely place it?) and then the 2nd block looks like it starts on the floor of the pool?

**Comment by arouinfar** [comment]
@jonathanolson the screenshot was used to illustrate an x-coordinate of where the block would appear. It can still bounce/sink as it drops into the pool.

**Comment by jonathanolson** [comment]
@arouinfar and @DianaTavares  how does the above change look?

**Comment by arouinfar** [comment]
Looks great, thanks @jonathanolson!

**Comment by DianaTavares** [comment]
I like it!
