### ISSUE TITLE
Mass/volume for blocks not always maintained in Studio/State

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/density#109]
**Test device**
MacBook Air (m1 chip)

**Operating System**
12.0.1

**Browser**
Safari15

**Problem description**
For https://github.com/phetsims/qa/issues/738

For the Studio wrapper, in the 2 Blocks Scene on the Intro Screen:
If styrofoam is chosen as the material for Block B and the mass/volume are at any values except MAX values, those values are not maintained once the sim is launched. In this case, the launched sim will always show max mass/volume values. I tried this in dev.18 and it worked properly.

**Steps to reproduce**
1. Go to the Intro screen and select 2 blocks 
2. Select styrofoam as the material for block B
3. Set the mass and volume of block B to anything but max values
4. Launch the sim--the mass of block B will by 1.50g and the volume will be 10.00L.

**Visuals**
<img width="799" alt="Screen Shot 2021-11-17 at 10 17 49 AM" src="https://user-images.githubusercontent.com/87318828/142243383-baedafd6-069b-4e68-ad30-c6af92db8e78.png">

<img width="963" alt="Screen Shot 2021-11-17 at 10 18 16 AM" src="https://user-images.githubusercontent.com/87318828/142243453-b569d88b-8075-45f7-ab0b-04534b249cef.png">

**Comment by Nancy-Salpepi** [comment]
Something similar is also seen in the State wrapper.

Steps to Reproduce:
1. In the State wrapper select the Intro screen
2. Set state rate = 0
3. Select 2 blocks
4. Change the material for block B to styrofoam
5. Decrease volume to 1 liter
6. Press 'Set State Now'
<img width="484" alt="Screen Shot 2021-11-17 at 4 26 17 PM" src="https://user-images.githubusercontent.com/87318828/142286216-cf7e02b2-0407-4afb-809f-5502b7673699.png">

**Comment by jonathanolson** [comment]
I believe this was fixed up, can you verify?

**Comment by Nancy-Salpepi** [comment]
@jonathanolson this issue looks fixed on master in studio and state wrappers. However, I am seeing a couple of other issues now on this screen in particular. See https://github.com/phetsims/density/issues/121 and https://github.com/phetsims/density/issues/119

**Comment by jonathanolson** [comment]
Those other issues are closed. Is there anything else left here?

**Comment by jonathanolson** [comment]
Thanks!
