### ISSUE TITLE
Block movement limited in Studio when Block visible property set to false

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/density#110]
**Test device**
MacBook Air (m1 chip)

**Operating System**
12.0.1

**Browser**
safari15

**Problem description**
For https://github.com/phetsims/qa/issues/738, in Studio:

In the Intro screen, when the visible property for Block A and Block B is set to false, the area where the blocks can move becomes limited to half the screen. Block material did not seem to be a factor with this issue. 

**Steps to reproduce**
1. In Studio, set density.introScreen.view.blockAControlPanel.visibleProperty and density.introScreen.view.blockBControlPanel.visibleProperty to false
2. Try and move a block to the right side of the screen

Movement is also limited once the sim is launched. 

**Visuals*
![blockmovementlimited](https://user-images.githubusercontent.com/87318828/142257349-6410dc8d-bf10-48f5-ae3c-435532a846fb.gif)
*

**Comment by jonathanolson** [comment]
Very nice catch! I believe I've fixed this with the above commit.

**Comment by Nancy-Salpepi** [comment]
Thanks @jonathanolson! It was very bizarre to see. haha. 
It looks good on master now.

**Comment by jonathanolson** [comment]
Thanks! (Code was using the control panel locations to set the invisible barrier, seems like assertions fired but the runtime sets it to 0 - i.e. the center)
