### ISSUE TITLE
'Same Volume' not working properly in State wrapper

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/density#111]
**Test device**
MacBook Air (m1 chip)

**Operating System**
12.0.1

**Browser**
Safari15

**Problem description**
For https://github.com/phetsims/qa/issues/738, in the State wrapper:

In the Compare Screen there seems to be a few issues with the  'same volume' property. If it is selected and the volume is changed using the slider, the masses change in the downstream sim and the color intensity of the blocks does not match. Also, if a block is in the water, it will continuously "jump" in the downstream sim. 

**Steps to reproduce**
1. In the State wrapper, go to the Compare Screen
2. Select 'Same Volume'
3. Place the blue block in the water
4. Move the slider back and forth--you will see that the masses change in the downstream sim
5. Move the slider to the max volume (10L)--you will see that the block in the water will continuously jump. 

**Visuals**

![samevolume](https://user-images.githubusercontent.com/87318828/142283352-c89da647-595b-441d-8ee0-7625a7552db3.gif)

**Comment by Nancy-Salpepi** [comment]
In the Studio Wrapper, with 'same volume' selected the masses are not maintained once the sim is launched. I don't see the "jumping" that I witnessed in State wrapper.
<img width="764" alt="Screen Shot 2021-11-18 at 8 18 58 AM" src="https://user-images.githubusercontent.com/87318828/142422741-10ba1b66-0094-4bac-8fc5-d24a3e357413.png">

**Comment by jonathanolson** [comment]
I believe the above commit handles this, can you verify?

**Comment by Nancy-Salpepi** [comment]
@jonathanolson looks good in Studio and State on master.

**Comment by jonathanolson** [comment]
Thanks!
