### ISSUE TITLE
Should teachers be able to set Density Readout visible property to false?

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/density#113]
For https://github.com/phetsims/qa/issues/738

For the Intro screen, I thought that teachers might want to have students calculate density on their own sometimes, but there is currently no way to uncheck the checkbox.
<img width="670" alt="Screen Shot 2021-11-18 at 2 47 58 PM" src="https://user-images.githubusercontent.com/87318828/142487267-7be5c82d-fafa-40f8-92f2-e290be2ffe3f.png">

**Comment by arouinfar** [comment]
Thanks @Nancy-Salpepi. It sounds like you'd like to hide the red/blue dynamic text that labels the density of the red/blue blocks along this scale. I don't think these values are instrumented individually, and the `densityReadout` is the entire contents of the `densityAccordionBox`.
![image](https://user-images.githubusercontent.com/8419308/142489894-c1246404-b55f-4593-b88b-ca09273262f9.png)

If users want to hide the entire `densityReadout` they should instead hide the `densityAccordionBox`. 

Please let me know if I've interpreted your request correctly @Nancy-Salpepi.

**Comment by Nancy-Salpepi** [comment]
You definitely interpreted by request correctly @arouinfar. Thanks for the clarification.
