### ISSUE TITLE
Switching between preset materials leads to incorrect mass and/or volume

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/density#114]
**Test device**
Dell
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/738. On the first screen, switching between the different materials (both for block a and block b) leads to the mass and volume listed on the sliders and the mass and volume shown in the play area to be different. Changing the sliders seems to fix this. Different materials are impacted in different ways.

**Visuals**
![incorrectchange](https://user-images.githubusercontent.com/41024075/142692970-18f02b92-2e69-4731-8108-97fac8112c53.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Density‬
URL: https://phet-dev.colorado.edu/html/density/1.0.0-dev.19/phet/density_all_phet.html
Version: 1.0.0-dev.19 2021-11-13 00:28:40 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36
Language: en-US
Window: 1280x649
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by KatieWoe** [comment]
Here is a more dramatic example:
![moredramatic](https://user-images.githubusercontent.com/41024075/142695563-3c749a83-8bc0-4183-b3d9-18062f227829.gif)

**Comment by jonathanolson** [comment]
Can you verify that this is fixed in master after the above commits?

**Comment by KatieWoe** [comment]
This looks good in master

**Comment by jonathanolson** [comment]
Thanks!
