### ISSUE TITLE
White bar in full screen mode in firefox

### ISSUE THREAD

**Issue by stemilymill** [phetsims/density#115]
For https://github.com/phetsims/qa/issues/738.

Dell laptop Win10 Firefox 94.0.1
I only see this in Firefox.

When I click Full Screen in the PhET menu, this white bar appears at the bottom of the screen above the navbar. The only way this doesn't happen is to clear the cache, refresh page, go to Intro screen, then enter full screen. 
If I clear cache, refresh page, go to Compare or Mystery screen and enter full screen, the bar appears. 
If I clear cache then first go to Intro screen > full screen (no white bar), then exit full screen, go to Compare or Mystery screen and enter full screen again, the white bar is back.

![firefox full screen white bar](https://user-images.githubusercontent.com/85511101/142698673-562d0789-287d-436a-9873-ba552b85f238.jpg)

Expected appearance:
![chrome full screen no white bar](https://user-images.githubusercontent.com/85511101/142699413-351cea79-2906-4559-8c79-5a739ea7e516.jpg)

Troubleshooting information:
!!!!! DO NOT EDIT !!!!

Name: ‪Density‬
URL: https://phet-dev.colorado.edu/html/density/1.0.0-dev.19/phet/density_all_phet.html
Version: 1.0.0-dev.19 2021-11-13 00:28:40 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:94.0) Gecko/20100101 Firefox/94.0
Language: en-US
Window: 1408x668
Pixel Ratio: 1.3636363636363635/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (ANGLE (Intel(R) HD Graphics Direct3D11 vs_5_0 ps_5_0, D3D11-27.20.100.9664))
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

**Comment by jonathanolson** [comment]
Should be fixed in master above, can you verify?

**Comment by stemilymill** [comment]
Looks fixed to me 👍

**Comment by KatieWoe** [comment]
Looks good in dev.20 on Win 11 (showed up on that platform as well)
