### ISSUE TITLE
Performance issues with multiple PhET-iO wrappers on iPad

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/density#116]
**Test device**
iPad Air 2
**Operating System**
15.1

**Browser**
safari

**Problem description**
https://github.com/phetsims/qa/issues/738

I'm seeing artifacts in many of the wrappers (ex-Multi, State, Data:text area, Screenshot) for the Intro and Compare Screens. 

**Steps to reproduce**
Ex from the State wrapper:
1. Go to the Intro Screen
2. Drag Block A around in the pool.  

**Visuals**
State wrapper:

https://user-images.githubusercontent.com/87318828/142937024-d7464ff2-3024-492f-906e-2d72efdbb809.mov

![Image (2)](https://user-images.githubusercontent.com/87318828/142937153-f9e81bd1-19f4-4c4b-9ade-7b0a72af27d2.jpeg)

**Comment by jonathanolson** [comment]
@arouinfar I'm interested in how much should be done for this... this seems like a browser-specific issue, and I don't have a great way of resolving it offhand.

**Comment by arouinfar** [comment]
@jonathanolson agreed. The artifacts are a bit unsightly, but I don't think it affects sim usability. I'm also not sure that this is a bug that would manifest for end-users of a PhET-iO product. I'll close as wontfix.
