### ISSUE TITLE
State wrapper may have trouble updating

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/density#118]
For https://github.com/phetsims/qa/issues/738. Seen on Win 11 Firefox in the State Wrapper. I have been unable to reproduce so far after refreshing the page.
The state wrapper stopped updating the state of the bottom sim consistently, and hitting the set state button didn't work. Things that would not update included the state of the second block and changing screens. I will update this issue if I find a reliable way to reproduce.
![statewrapperchanges](https://user-images.githubusercontent.com/41024075/143102801-c54b190b-e0e5-4b85-beaf-8d833b1af265.gif)

**Comment by KatieWoe** [comment]
After finishing the issue, I came back to the state wrapper to see this bug had returned. It may have something to do with the time spent on the page. This bug was appearing in the console.
<img width="960" alt="time" src="https://user-images.githubusercontent.com/41024075/143114019-6fdc744f-0558-4622-94f3-2be89356ee07.png">

**Comment by jonathanolson** [comment]
The stack trace seems similar to a bug I fixed earlier. I'm curious if this can happen again (or if it does happen, digging into the state of the sim).

**Comment by KatieWoe** [comment]
I left the state wrapper to sit for a few minutes on Win 11 Firefox on master and this issue didn't seem appear. If this was the way to reproduce it looks like it might be fixed.

**Comment by jonathanolson** [comment]
Perhaps let's see if it occurs in the next round of testing?

**Comment by KatieWoe** [comment]
Looks fixed in dev.20
