### ISSUE TITLE
Reset All in Studio/State keeps 2 blocks button selected

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/density#119]
**Test device**
MacBook Air (m1 chip)

**Operating System**
12.0.1

**Browser**
chrome

**Problem description**
In State on master, while verifying https://github.com/phetsims/density/issues/109, I noticed that when pressing the reset button, block B and the block B panel disappear in the upstream sim, but the 2 blocks button is still selected. The downstream sim still shows 2 blocks. The same thing happens in the studio wrapper. 
 
**Steps to reproduce**
In State:
1. Go to the intro screen and select 2 blocks
2. Press the reset all button

In Studio:
1. Go to the intro screen and select 2 blocks
2. Press the reset all button
3. Press 'Preview Sim' button

**Visuals*
![2blocksbutton](https://user-images.githubusercontent.com/87318828/144514463-953ccde2-162e-49c6-976d-83904395e044.gif)
*

**Comment by jonathanolson** [comment]
I believe this should be fixed with the above commit, can you verify?

**Comment by Nancy-Salpepi** [comment]
This looks good on master now.

**Comment by jonathanolson** [comment]
Thanks!
