### ISSUE TITLE
not allow to trow the blocks out of the sim

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/density#12]
Users can move the blocks outside the sim and lose them
![blocks](https://user-images.githubusercontent.com/26031501/77708072-a86c5d00-6f8c-11ea-917f-293a5339cdb8.gif)

**Comment by jonathanolson** [comment]
How is this planned to be resolved? Invisible walls around the edge of the sim viewport (including at the top? just the sides?) A button to return anything that goes off-screen?

**Comment by DianaTavares** [comment]
I like the solution of the flash sim, invisible walls at the left and right edge of the sim viewport, but the top is not necessary.

**Comment by jonathanolson** [comment]
Should be implemented in master.

**Comment by DianaTavares** [comment]
Nice!! I see two strange behaviors: 
1) Users can lose the second block if the block is moved behind the panel. Probably we can solve this moving the wall in the first screen to the place where the panel is:
![lose block2](https://user-images.githubusercontent.com/26031501/80020383-8e943c00-849e-11ea-9c23-12699cbf54ac.gif)

2) if the user moves fast the block against the invisible wall, it jumps a lot. Can the collision between the wall and the block be inelastic? 
![jumpingBlock](https://user-images.githubusercontent.com/26031501/80020452-ad92ce00-849e-11ea-8245-91ca5389241d.gif)

**Comment by jonathanolson** [comment]
I believe I've been able to resolve both of those issues in master, can you check how it behaves?

**Comment by arouinfar** [comment]
The behavior is looking good to me @jonathanolson.

**Comment by DianaTavares** [comment]
The behavior is good for me too! I think this issue is complete!
