### ISSUE TITLE
Choosing 'custom' freezes the sim in master

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/density#121]
**Test device**
MacBook air (m1 chip)

**Operating System**
12.0.1

**Browser**
chrome

**Problem description**
While verifying https://github.com/phetsims/density/issues/109 on master, I noticed that the sim freezes in the studio and state wrappers when 'custom' is selected. 

**Steps to reproduce**
1. Go to either wrapper
2. On the intro screen select 2 blocks
3. Select 'custom' for block B --sim freezes

**Visuals**
<img width="1402" alt="Screen Shot 2021-12-02 at 6 11 33 PM" src="https://user-images.githubusercontent.com/87318828/144517814-081ac5dc-c7a8-4740-81ca-fd62c7dd3200.png">

**Comment by jonathanolson** [comment]
I believe this should be fixed with the above commit.

**Comment by Nancy-Salpepi** [comment]
This is also fixed on master :)

**Comment by jonathanolson** [comment]
Thanks!
