### ISSUE TITLE
Density - Publish 1.0 with PhET-iO

### ISSUE THREAD

**Issue by markgammon** [phetsims/density#123]
Publish Density simulation with both PhET and PhET-iO brands. 

- [ ] https://github.com/phetsims/density/issues/1
- [ ] https://github.com/phetsims/density/issues/76

**Comment by zepumph** [comment]
This is published, but we are going to do a MR that includes these three improvements:

* https://github.com/phetsims/studio/issues/243
* https://github.com/phetsims/studio/issues/245
* https://github.com/phetsims/phet-io/issues/1835

**Comment by zepumph** [comment]
We have since moved away from a Maintenance Release, we are instead working towards a batch release from master, see https://github.com/orgs/phetsims/projects/44

**Comment by arouinfar** [comment]
We published 1.0 in January 2022 and opened https://github.com/phetsims/density/issues/108 for the 1.1 publication. We can close this issue.
