### ISSUE TITLE
Labels on mystery blocks need larger maxWidth

### ISSUE THREAD

**Issue by arouinfar** [phetsims/density#125]
@jonathanolson one of the client requests is to be able to change the label on the blocks in the Mystery Screen. Currently, that's possible using the block's `nameProperty`, such as `density.mysteryScreen.model.blockSets.random.blockA.nameProperty`. 

However, the labels are super small, and can really only accommodate 2-3 characters without hitting the maxWidth and becoming unreadable. I don't think being limited to a few characters will meet the client's needs.
![image](https://user-images.githubusercontent.com/8419308/146613564-c2020d56-7bf5-4a5a-92f6-c7b0ce7dc055.png) ![image](https://user-images.githubusercontent.com/8419308/146613551-40423796-3465-49ea-ad9e-27ab2ddc3fca.png) ![image](https://user-images.githubusercontent.com/8419308/146613593-3dcb3982-3b1f-41bd-ad1b-28e06beae23b.png)

Would it be possible to leverage dynamic layout so that these labels could expand as needed?

**Comment by jonathanolson** [comment]
Implemented above (needed some WebGL reworking for the mobius code). Can you verify? A maxWidth still applies.

**Comment by arouinfar** [comment]
Looks good in master, thanks @jonathanolson.

![image](https://user-images.githubusercontent.com/8419308/147014779-e2f4abd9-3a7c-4892-833f-36f2cb62ab49.png)
