### ISSUE TITLE
Updates to phetioDocumentation

### ISSUE THREAD

**Issue by arouinfar** [phetsims/density#126]
In #99 I discovered that there were a few properties that would benefit from phetioDocumentation.

@jonathanolson here is the suggested text, please feel free to edit as necessary.

- [x] `comboBoxMaterialProperty`: Current material of the block. Changing the material will result in changes to the mass, but the volume will remain the same.
- [x] `materialEnumProperty`: Current material of the block. Changing the material will result in changes to the mass, but the volume will remain the same.
- [x] `customDensityProperty`: Density of the block when the material is set to “CUSTOM”.
- [x] `massProperty`: Current mass of the block. Changing the mass will result in changes to the material (and therefore density), but the volume will remain the same. 
- [x] `volumeProperty`: Current volume of the block. Changing the volume will result in changes to the mass, but will not change the material or density.

**Comment by jonathanolson** [comment]
Implemented, can you verify?

**Comment by arouinfar** [comment]
@jonathanolson looks pretty good. I wrote the phetioDocumentation with the blocks in mind, but forgot about `scale.massProperty` and `scale.volumeProperty`. Would it be possible to remove the phetioDocumentation for the scale? Since the scale isn't adjustable, I think the phetioID provides a sufficient enough description of these properties.

**Comment by jonathanolson** [comment]
I believe that should be handled above, can you verify?

**Comment by arouinfar** [comment]
Looks good, thanks @jonathanolson!
