### ISSUE TITLE
Block position doesn't reset with multitouch

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/density#127]
**Test device**
iPad Air 2

**Operating System**
15.2

**Browser**
safari

**Problem description**
For https://github.com/phetsims/qa/issues/758

If I am holding a block with one finger while pressing the Reset All Button with another, the block position doesn't reset. This occurs on all screens and also occurs with the Random Blocks Reset Button on the Mystery Screen. 

**Steps to reproduce**
1. On the iPad, go to any screen, hold a block in the air or in the pool with one finger
2. Press the reset button 

**Visuals**

https://user-images.githubusercontent.com/87318828/147955614-c47fcf84-8b76-42b3-b507-6aec778737a2.mov

https://user-images.githubusercontent.com/87318828/147955713-2c0cf2c5-6bb7-4d8f-8f39-0a8927ef70a0.MP4

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Density‬
URL: https://phet-dev.colorado.edu/html/density/1.0.0-rc.1/phet/density_all_phet.html
Version: 1.0.0-rc.1 2021-12-22 19:13:46 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36
Language: en-US
Window: 1376x690
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by jonathanolson** [comment]
I believe the above patch will work, but I have no way currently of testing multitouch. @Nancy-Salpepi can you verify in master? I've already patched the release branch for it.

**Comment by Nancy-Salpepi** [comment]
Hi @jonathanolson 
It still looks the same on Master (I used a private window, cleared my history and hit "pull all").

**Comment by jonathanolson** [comment]
Ok, thanks! I'll look at using my phone for testing.

**Comment by jonathanolson** [comment]
Identified the problem, tested with my phone and looks fixed. @Nancy-Salpepi can you verify on master? It's also patched in release branch.

**Comment by Nancy-Salpepi** [comment]
Looks good @jonathanolson!

**Comment by Nancy-Salpepi** [comment]
Looks good in RC.3!
