### ISSUE TITLE
Include `?autoselectSupported` in phet-io-guide.md

### ISSUE THREAD

**Issue by arouinfar** [phetsims/density#128]
For https://github.com/phetsims/qa/issues/758

The autoselect feature in Studio is available with `?autoselectSupported` in the release branch. The feature is still under development in https://github.com/phetsims/studio/issues/243, but I think it would be useful for clients in its current state. Sharing it with clients may also generate some useful feedback.

@kathy-phet should we add `?autoselectSupported` to the list of query parameters in [phet-io-guide.md](https://github.com/phetsims/phet-io-client-guides/blob/master/density/phet-io-guide.md)? (Note that the link in the table below is a templated link which gets created during the build process.)

| Query Parameter | Values | Description | Examples |
| --- | --- | --- | --- |
| `autoselectSupported` | N/A | The autoselect feature is still under development, but available as a prototype. When enabled, pressing the alt/option key while hovering over a sim element will autoselect it in the PhET-iO Studio tree. Autoselect currently only works with elements that have an enabled input listener.  | `autoselectSupported` <br>  [Studio]({{STUDIO_PATH}}?autoselectSupported) |

**Comment by kathy-phet** [comment]
Hi Amy, I think yes we should include it. 

Overall, I like the wording, but would modify slightly to address checking the checkbox versus using the alt/option key mode .... 
The autoselect feature is still under development, but available as a prototype. When query parameter ?autoselectSupported is used, the feature can be turned on in continuous mode (by checking the checkbox) or in as-needed (by pressing the alt/option key while hovering over a sim element). When activated, the feature will autoselect that element in the PhET-iO Studio tree. We find using the alt/option key mode more convenient. Autoselect currently only works with elements that have an enabled input listener.

Please tweak to improve - this was just a first pass. Thanks!

**Comment by arouinfar** [comment]
Thanks @kathy-phet! I made a few minor tweaks to your description and committed it to master.

@jonathanolson this commit will need to be cherry-picked into the release branch.

**Comment by jonathanolson** [comment]
Patched into the release branch.

**Comment by arouinfar** [comment]
Thanks @jonathanolson. I don't have a way to verify until the next RC is published, so back to you to tag for verification in the RC issue.

**Comment by Nancy-Salpepi** [comment]
?autoselectSupported has been added to the PhET-iO guide.
I gave it a spin with Mac + chrome/safari and I love this feature!
