### ISSUE TITLE
Need to delay sim startup for three.js texture loading

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/density#13]
Since we're creating certain things like screen icons at a certain point, we really want to have three.js textures loaded before moving on with SimLauncher's creation of the screens. Otherwise we have unloaded image data at the start:

<img width="391" alt="Screen Shot 2020-03-26 at 10 17 06 PM" src="https://user-images.githubusercontent.com/480878/77721139-90f29b80-6faf-11ea-93a4-4ffbb08bdd6f.png">

**Comment by jonathanolson** [comment]
@ariel-phet the above change to SimLauncher should at a minimum be reviewed by someone familiar with the image/phetioEngine loading sequence (@samreid or @zepumph I believe), and it should be discussed if there's a better way to handle lock creation in general for the startup sequence.

**Comment by samreid** [comment]
I'd love to hear from @zepumph about this.  We discussed a more general mechanism for locking in SimLauncher, but settled on doing something specific to images and dynamic modules.  Now that we have other use cases like this texture, should we generalize this into a single pattern?

**Comment by jonathanolson** [comment]
> Now that we have other use cases like this texture, should we generalize this into a single pattern?

I think that would ideally be best.

**Comment by chrisklus** [comment]
From 4/2/20 dev meeting:

@samreid is going to take on unifying images, textures, phetioEngine, and brand with a time frame of about 2 weeks, and then pass it off to @jbphet to investigate the sound aspect.

**Comment by samreid** [comment]
Density is working well, so we'll close this issue and continue in https://github.com/phetsims/joist/issues/621
