### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/density#130]
For https://github.com/phetsims/qa/issues/758

@jonathanolson here are the results of the memory tests. I was not able to record data after the tenth heap snapshot--either the console would close automatically or error messages would appear in the console.( I tried more than once, but always got the same results.)

Density PhET Brand:
<img width="463" alt="Screen Shot 2022-01-03 at 7 29 07 PM" src="https://user-images.githubusercontent.com/87318828/147996315-4d05d570-80b8-41d0-b45d-359689ea96fa.png">

Density PhET-iO Brand:
<img width="512" alt="Screen Shot 2022-01-03 at 7 57 48 PM" src="https://user-images.githubusercontent.com/87318828/147996340-c026c740-e752-43f2-8909-0d680e316a1c.png">

Error message:
<img width="468" alt="Screen Shot 2022-01-03 at 7 58 32 PM" src="https://user-images.githubusercontent.com/87318828/147996371-23697c03-9d03-445c-95df-2537066c5b4b.png">

**Comment by jonathanolson** [comment]
I believe this should be fixed on master and the release branch, can you verify on master?

**Comment by Nancy-Salpepi** [comment]
Looks good on Master @jonathanolson 

PhET brand:
<img width="467" alt="Screen Shot 2022-01-05 at 8 43 41 AM" src="https://user-images.githubusercontent.com/87318828/148234150-d8be18ee-8df8-4933-911e-52581a428bd5.png">

PhET-iO brand:
<img width="467" alt="Screen Shot 2022-01-05 at 9 28 27 AM" src="https://user-images.githubusercontent.com/87318828/148234206-8f7b45fb-b299-4c43-a9da-957a5a1afcbb.png">

**Comment by KatieWoe** [comment]
Memory test for rc.3 was done here: https://github.com/phetsims/qa/issues/759#issuecomment-1007724368.
Looks good, closing.
