### ISSUE TITLE
Sim screenshots

### ISSUE THREAD

**Issue by arouinfar** [phetsims/density#131]
@DianaTavares please suggest some screenshots (1 main, 3 alternates), and I can take them at the correct resolution and commit them. If you don't have a preference, let me know, and I can create some scenarios.

**Comment by arouinfar** [comment]
@jonathanolson the screenshots are ready, but I can't commit them since there isn't an assets directory, so back to you.

[density-screenshot.png](https://user-images.githubusercontent.com/8419308/149040315-53de9a73-32c5-4b39-9a35-d775343f3a43.png)
[density-screenshot-alt1.png](https://user-images.githubusercontent.com/8419308/149040316-367ad88d-848b-486f-8c95-ebb15b8475d9.png)
[density-screenshot-alt2.png](https://user-images.githubusercontent.com/8419308/149040318-af6d09b5-d5ef-4c3d-b533-6b9e0f227ab4.png)
[density-screenshot-alt3.png](https://user-images.githubusercontent.com/8419308/149040319-c813f15b-8bf6-4796-963e-0c49e16e612b.png)

**Comment by arouinfar** [comment]
@jonathanolson looks like I can commit the assets directory containing the screenshots from the GitHub interface, so I'll go ahead and take care of the commits.

**Comment by arouinfar** [comment]
@jonathanolson I added the assets directory and sim screenshots to master and 1.0 in the above commits.

**Comment by jonathanolson** [comment]
Thanks!
