### ISSUE TITLE
Instrument text lablels in blocksRadioButtonGroup

### ISSUE THREAD

**Issue by arouinfar** [phetsims/density#134]
This was noticed while reviewing Buoyancy in Studio for https://github.com/phetsims/buoyancy/issues/51.

The Compare and Mystery screens have a RadioButtonGroup to control the block set. 
<img width="135" alt="image" src="https://user-images.githubusercontent.com/8419308/170183412-ce5b8f56-8f06-403c-bf9d-26cf85709180.png"> 
<img width="109" alt="image" src="https://user-images.githubusercontent.com/8419308/170183557-66907de0-88c5-4ed0-b542-44fc12a3cdea.png">

Clients may want to supply their own label, so let's instrument the text labels for these radio buttons.

**Comment by jonathanolson** [comment]
Implemented in both sims (and fixed alignment), can you see how it looks?

**Comment by arouinfar** [comment]
Looks great, thanks @jonathanolson
