### ISSUE TITLE
Large volume blocks created with SetValue can remove liquid from the pool

### ISSUE THREAD

**Issue by stemilymill** [phetsims/density#136]
for https://github.com/phetsims/qa/issues/820

Win10 Chrome 103.0.5060.114

When using SetValue to make the block very large, the block seems to push the liquid out of the pool so that when the block is removed from the pool, there is much less liquid.

**Remaining liquid after large block has been removed from pool**
![density setvalue water pool](https://user-images.githubusercontent.com/85511101/180261971-8702df6a-bcbd-402a-b6ab-7e9ad2244f45.jpg)

**cube volume**
![cube setvalue  12](https://user-images.githubusercontent.com/85511101/180261913-e6b8259c-0a0c-4cb6-89bf-a44145eb53e7.jpg)

on slack, @arouinfar suggested that the range be capped at 10L instead of extending to infinity. There may be other instances of values which need range limits.

**Comment by KatieWoe** [comment]
The blocks behave oddly (falling slowly for instance) and don't change size if you enter a volume of 0, which is also within the given range. A console error occurs when you try this.
<img width="960" alt="atzero" src="https://user-images.githubusercontent.com/41024075/180265584-26f29b20-4e37-41e3-b817-34d435099f2d.png">

**Comment by arouinfar** [comment]
@jonathanolson can the `volumeProperty` be bounded to [1, 10] L? This is the range accessible with the slider, so it seems appropriate to limit the model too. The implications for blocks outside of this range are problematic, as reported by QA.

We can continue to use `"range": { "min": 5e-324, "max": "POSITIVE_INFINITY" }` for the mass and density, since we should be keeping volume constant.

**Comment by jonathanolson** [comment]
I added [1, 10] L limits for all of the masses in Density. It needs to be set per-mass, since a cube in Buoyancy is OVER that limit, and cones can go UNDER that limit.

@arouinfar can you see how this looks?

**Comment by arouinfar** [comment]
Thanks @jonathanolson. Everything looks good in Density.

There are a few cases in Buoyancy that look odd. For example:
`buoyancy.applicationsScreen.model.block.volumeProperty` doesn't have the same range as the corresponding Volume slider. `buoyancy.applicationsScreen.model.boat.volumeProperty` is similar, the range is infinite, but for some reason it is read-only, which seems odd.

Let me know if you would like me to do a more in-depth review of Buoyancy, or if it's too early for that sort of review.

**Comment by jonathanolson** [comment]
> Let me know if you would like me to do a more in-depth review of Buoyancy, or if it's too early for that sort of review.

This sounds helpful, what ranges should specific things have in Buoyancy?

**Comment by arouinfar** [comment]
Sounds good @jonathanolson. I've made a note over in the https://github.com/phetsims/buoyancy/issues/51 to review the `volumeProperty` in more detail.

Since the core issue here has been addressed, I'll go ahead and close.
