### ISSUE TITLE
Potential difficulty in the same mass scene

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/density#139]
**Device**
Dell
**OS**
Win 11
**Browser**
Chrome
**Problem Description**
For https://github.com/phetsims/qa/issues/820.
On the compare screen, the example guide states that density and volume can be changed, and mass will change to accommodate while the other stays constant. This does appear to be the behavior. However, the same mass scene can face some difficulties when trying to make customizations. It is still possible, but is more complicated to get changes to stick since all 4 masses should be the same. Design may need a second pass in this scene.

**Comment by arouinfar** [comment]
Thanks @KatieWoe. I don't think there is anything we should do to change the way the model behaves when customizing the `materialProperty` or `volumeProperty`. However, I added additional clarification to the Examples doc, and it now reads:

> The blocks can also be customized through the data entry interface in Studio or an API. However, only the "CUSTOM" material is available on this screen, and the blocks cannot take on the realistic textured appearance of another material such as ice or brick. Additionally, there is no enforcement of “Same Mass”, “Same Volume”, or “Same Density” in the model, so take care when making customizations. 
>
>The `materialProperty` can be used to set the density or change the block’s color (using the `staticCustomColor`). To set the volume, use the `volumeProperty`. The mass will be derived from the density and volume. When customizing blocks within the “Same Mass” scene, we recommend first setting the `volumeProperty` and then calculating the density required for the block to have the desired mass.
