### ISSUE TITLE
Use dynamic layout on Compare Screen NumberControl panels

### ISSUE THREAD

**Issue by arouinfar** [phetsims/density#141]
Related to https://github.com/phetsims/qa/issues/820

In https://github.com/phetsims/density-buoyancy-common/commit/6102ec1424052945ac35394d8d93e06e0b389276 @jonathanolson added dynamic layout to the  NumberControlPanels on the Compare Screen.

However, there seems to be some sort of regression because the panel is not resizing to fit the contents in master or in 1.1.0-dev.2
![image](https://user-images.githubusercontent.com/8419308/180830349-b5208ab7-cc95-488d-b525-7dff26dc45b1.png)

**Comment by jonathanolson** [comment]
This should be handled above, @arouinfar can you test it out?

**Comment by arouinfar** [comment]
Thanks @jonathanolson. Overall, looking good, though I think it would be nice to maintain some padding between the label an the NumberDisplay. It looks a bit cramped:
<img width="118" alt="image" src="https://user-images.githubusercontent.com/8419308/186018916-1e046382-1283-4b0e-b85e-57ecd127b04a.png">

**Comment by jonathanolson** [comment]
I believe the NumberControl should now have spacing between the title and NumberDisplay, can you verify?

**Comment by arouinfar** [comment]
Thanks @jonathanolson, it looks much better now.
<img width="113" alt="image" src="https://user-images.githubusercontent.com/8419308/186984903-0c1f80e8-127b-46f7-b6e1-b92cface7105.png">
