### ISSUE TITLE
Review string reachability and tandems in phet-io

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/density#145]
I'm curious if I should be adding tandems to currently un-tandem'ed string "derived" Properties

**Comment by arouinfar** [comment]
@jonathanolson I reviewed Density on master, with a focus on dynamic layout and string discoverability in the Studio tree.

Generally, I expect to see strings related to UI components like sliders and radio buttons linked in the tree, which I see already in Density. I would also expect to see things like panel/AccordionBox titles instrumented/linked too (which I don't). I would not, however, expect to see all of the strings related to the Density Table exposed in the Studio Tree.

Overall, I think Density is looking good. There are a few places where string discoverability could be better.
- [ ] `blocksPanel` title  link to `blocksStringProperty` (Compare & Mystery screens)
- [ ]  `densityTableAccordionBox` title link to `densityTableStringProperty`
- [ ] `densityAccordionBox` title link to `densityReadoutStringProperty`

**Comment by arouinfar** [comment]
@samreid this also looks like an issue you can handle (if time allows).

I reviewed dynamic strings/layout in Density, and it generally all looked good. I found a few places where it would be nice to link the strings to the view. See https://github.com/phetsims/density/issues/145#issuecomment-1468969034 for the checklist.

**Comment by samreid** [comment]
This issue was still assigned to me from the prior iteration, and I considered unassigning it until a density-focused iteration.  But I checked and it seemed straightforward to instrument the Text instances with those strings, so I decided to go for it. @arouinfar or @jonathanolson do not feel obligated to spend time on this if it is not in line with your current priorities.

**Comment by samreid** [comment]
The API file is very stale. I'll regenerate it before starting.

**Comment by samreid** [comment]
I instrumented the `titleText` for those 3 checkboxes, @arouinfar can you please review the tandem names and structure?

**Comment by arouinfar** [comment]
Thanks @samreid! 

> `blocksPanel` title  link to `blocksStringProperty` (Compare & Mystery screens)

Looks good for Compare, but was missed on Mystery.

@jonathanolson on the Mystery screen, can you add `blocksPanel.titleText` and link it back to the `blocksStringProperty`?  Please follow the pattern used on the Compare screen:
<img width="235" alt="image" src="https://user-images.githubusercontent.com/8419308/228059375-90a359e6-70bf-4592-bbc1-1a80ef843634.png">

**Comment by jonathanolson** [comment]
Implemented above, can you verify?

**Comment by arouinfar** [comment]
Looks good, thanks @jonathanolson!
