### ISSUE TITLE
Add 2nd Unit Option for European Locale

### ISSUE THREAD

**Issue by RVieyra** [phetsims/density#147]
Diana,

I have spoken with @kathy-phet based on some user feedback from Europe (Italy, specifically), in which density is regularly reported as kg/m^3, not kg/L. Kg/m^3 would produce numbers far _too small_ for this sim, but kg/dm^3 is a better option that is more in line with Italian norms.

@kathy-phet would like to ask the design team to consider adding kg/dm^3 as a _second option_ for units within this sim as part of the PhET iO update later this year.

Please let me know if you have any questions.

**Comment by DianaTavares** [comment]
I like the idea!  I agree with this being added. It doesn't require any changes in the design because it is the same number. Just all the L will change to dm^3.  Even in the translation utility, I think the Italian can change the L for dm^3, but I think is better to have a quarry parameter for that. No sure what are the actions that I need to do to continue with this plan.

**Comment by RVieyra** [comment]
Hi Diana,

To be clear, we are hoping for having the _two options_ within the simulation, so people could toggle between the two.

I agree with @kathy-phet that we should not use the Translation Utility to modify units, so if any other translator asks, let's tell them to _not_ make unit changes there.

**Comment by arouinfar** [comment]
Density will likely be republished with PhET-iO in the near-ish future, so I think it would be good to consider how to address this request. This looks like a pretty straightforward case of adding a control to the Preferences dialog with a corresponding query parameter.

Beer's Law Lab is a recent example of this. The Preferences dialog contains controls for beaker and concentration meter units, which are respectively settable with the `beakerUnits` and `concentrationMeterUnits` query parameters.
<img width="1371" alt="image" src="https://user-images.githubusercontent.com/8419308/225139381-c9e25b50-16b2-4145-883b-0ba86bc07913.png">

For Density, we could have a RadioButtonGroup called "Volume Units" with options of L and dm<sup>3</sup>. The corresponding query parameter could be `volumeUnits`. I'm not sure value we would use for dm<sup>3</sup>, here are few options:
* `cubicDecimeters`
* `dmCubed`
* `decimetersCubed`

@DianaTavares what do you think?

**Comment by DianaTavares** [comment]
Love the idea!  And I like the option of `decimetersCubed`. It is large but very explicit. 
Do I have to do something else to go with this?

**Comment by arouinfar** [comment]
Discussed with @DianaTavares and @jonathanolson yesterday and we decided to include this feature in the 1.1 release.

- [ ] Add Volume Units control to the Simulation tab of the Preferences dialog
![image](https://user-images.githubusercontent.com/8419308/228318515-eabdadb2-3d2d-45f4-b565-c32ddd55a406.png)

- [ ] Create `volumeUnits` query parameter that accepts values `liters` (default) and `decimetersCubed`.

- [ ] The Volume Units control and underlying property (let's call it `volumeUnitsProperty`) should be instrumented. Concentration is a good example of this. The properties powering the Preferences can be found in the tree under `global.model.preferences`.

- [ ] `volumeUnitsProperty` should be `phetioFeatured: true`. This can be done internally in sim code or by manually adding it to the overrides file. (As of https://github.com/phetsims/phet-io/issues/1873#issuecomment-1460709508, we're moving away from overrides and internalizing phetioFeatured, so I think either method is fine.)

**Comment by jonathanolson** [comment]
Note: Usually I'd create string patterns that just took units, but I'm having to duplicate a lot of strings so that we don't lose those in translations after the updates.

**Comment by jonathanolson** [comment]
It also looks like it might link multiple string Properties to things when only one is used.

**Comment by jonathanolson** [comment]
<img width="196" alt="image" src="https://user-images.githubusercontent.com/480878/228711074-d859fb52-505d-4608-887b-2fc05b8bdff1.png">
Some layout issues in Buoyancy that might require some design work.

**Comment by jonathanolson** [comment]
Initial implementation done. @arouinfar and @DianaTavares can you see how this looks?

**Comment by arouinfar** [comment]
@jonathanolson I reviewed Density and Buoyancy on master and the behavior matches everything I asked for in https://github.com/phetsims/density/issues/147#issuecomment-1487332934, thanks! The tree structure looks good, as do the links back to the stringProperties.

> Some layout issues in Buoyancy that might require some design work.

I think this issue existed before this change. There is some overlap for L, but it definitely gets worse in dm<sup>3</sup>. We can probably optimize the `maxWidth` for the L case, and live with dm<sup>3</sup> shrinking a bit.

**Comment by DianaTavares** [comment]
I look amazing @jonathanolson 
the density readout in buoyancy is going to change its place (here is the issue related with it: [https://github.com/phetsims/buoyancy/issues/32](https://github.com/phetsims/buoyancy/issues/32)) and in this new place, the change of units will not be a problem. 
![image](https://user-images.githubusercontent.com/26031501/228901104-b9a8fa55-5bfc-491b-869b-7e4714065fe1.png)




Then we can close this issue!

**Comment by DianaTavares** [comment]
I re-open because I don't know what is the next steps:

- Now the sim needs to be republished? 
- I can update the teacher tips, but once the sim is re-published

**Comment by arouinfar** [comment]
> I re-open because I don't know what is the next steps:

> Now the sim needs to be republished?

Yes, we need to republish the simulation so users can use this new feature. We are planning to republish Density with PhET-iO in the near future, and we will also republish the standard phet-brand version as part of that process. I'll tag this issue as `fixed-awaiting-deploy` so we don't lose track of it. 

> I can update the teacher tips, but once the sim is re-published

Great idea! I'll open a separate issue for that.

**Comment by Nancy-Salpepi** [comment]
After discussing with @arouinfar on slack, `beakerUnitsControl` should be volumeUnitsControl.

**Comment by jonathanolson** [comment]
Done above, @arouinfar does that look good?

**Comment by arouinfar** [comment]
Looks good, thanks @jonathanolson!

**Comment by oliver-phet** [comment]
Just adding user feedback here that `m³` is preferable to `dm³`:

> Could the simulation have the SI units for density as kg.m^-3 with volume in m^3, as L (litres) and dm^3, though common, are confusing for some students who are using the SI units, and the conversion can be tricky.
> I am aware of the conversion from L to dm^3, but though commonly used, these are not the main units used to measure volume in m^3.
