### ISSUE TITLE
Mystery Screen: Random block set has inappropriate volume range

### ISSUE THREAD

**Issue by arouinfar** [phetsims/density#154]
For #150 

On the Mystery Screen, we allow clients to directly set the `massProperty` of the blocks. When the mass is changed in this way, the volume of the block automatically changes to maintain a constant density. The examples doc cautions clients to make sure that the resultant volume is within range (1-10 L). However, there is no enforcement of this within Studio, but there used to be.

In https://github.com/phetsims/density/issues/135#issuecomment-1228954133 I detailed an example that would result in an out-of-range volume and there was previously an error in Studio, so this looks like a regression.

1. On the Mystery Screen, autoselect a block and set `customDensityProperty` to 100000 kg/m^3.
2. Set its `massProperty` to 1000 kg.
3. The required volume is 100 L, well beyond the allowed range. However, Studio does not block Set Value and this is the result:

<img width="562" alt="image" src="https://user-images.githubusercontent.com/8419308/226745423-5fbb77c6-1052-497d-9318-29f6bf588ef3.png">

**Comment by arouinfar** [comment]
Looks like the culprit is that `volumeProperty.rangeProperty` is no longer 1-10 L on the Mystery Screen.
<img width="790" alt="image" src="https://user-images.githubusercontent.com/8419308/226992544-3d75dbdf-ced9-4ccc-a8c1-57a88baca31d.png">

**Comment by arouinfar** [comment]
It seems like this issue is limited to just the "Random" set of blocks. The other sets on the Mystery screen have the appropriate volume range.

**Comment by jonathanolson** [comment]
I added the range constraints above to the random masses, but this only triggers an internal assertion (I guess that isn't detected by phet-io?)

Presumably we'd have to do something a bit crazy, like dynamically adjusting the range of the massProperty based on the customDensityProperty, and the customDensityProperty based on the massProperty in order to enforce the volume constraint. Is that type of thing desired?

**Comment by arouinfar** [comment]
> I added the range constraints above to the random masses

Thanks @jonathanolson. Every block now has an appropriate `volumeProperty.rangeProperty`.

> but this only triggers an internal assertion (I guess that isn't detected by phet-io?)

That is so strange! I wonder why PhET-iO was previously able to detect the assertion, as in https://github.com/phetsims/density/issues/135#issuecomment-1228954133. 
> <img src="https://user-images.githubusercontent.com/8419308/228736390-e9811902-49b5-44eb-93e7-00cf3eda9290.png" width=300>

PhET-iO common code has changed significantly since then, so it's possible that it's just the new normal rather than an actual regression.

> Presumably we'd have to do something a bit crazy,

No need to do anything crazy. The examples doc already cautions clients to make sure that the resultant volume will be in range when updating the `massProperty`. If this is just the new normal, that's okay.

However, it might be worth checking in with @samreid or @zepumph for a second opinion just in case, though. @jonathanolson can you reach out?

**Comment by zepumph** [comment]
Let's talk when the time and priority arises, I don't think async is best for something like this.

**Comment by arouinfar** [comment]
> Let's talk when the time and priority arises, I don't think async is best for something like this.

As far as Density goes, this is a high priority @zepumph. 

It would be nice to understand why Studio can no longer detect the out-of-range value downstream. If this is just the expected behavior due to other changes in PhET-iO common code, that's fine. However, if this is unexpected, I think it deserves some investigation to figure out why the behavior has changed.

**Comment by samreid** [comment]
I launched Density | Studio and followed the first step:

> On the Mystery Screen, autoselect a block and set customDensityProperty to 100000 kg/m^3.

It resulted in this error dialog in studio:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/679486/230496631-51fa605e-595e-429c-a3fa-81787526c3b7.png">

@arouinfar what else needs to be done for this issue?

**Comment by samreid** [comment]
@jonathanolson and I worked on it, and added a custom validator. We have a much nicer error message like this:

<img width="464" alt="image" src="https://user-images.githubusercontent.com/679486/230506497-0a02bbd4-c88a-4624-b37b-2a4243ba58ce.png">

Hoping to commit soon.

**Comment by samreid** [comment]
@jonathanolson and I added the guard I described above. We tested it well in the Mystery Screen on the massProperty. @arouinfar can you please test?

**Comment by arouinfar** [comment]
@samreid @jonathanolson everything looks good is master, thanks!

For future reference, this is what the warning currently looks like:
![image](https://user-images.githubusercontent.com/8419308/230659058-fad08efa-3188-4096-95fd-f36715b77f0a.png)
