### ISSUE TITLE
`customDensityProperty` is missing units

### ISSUE THREAD

**Issue by arouinfar** [phetsims/density#156]
For #150 

<img width="984" alt="image" src="https://user-images.githubusercontent.com/8419308/227101618-6939214c-da9d-40fe-bd53-59e7915e388f.png">

`customDensityProperty` should have units of kg/m<sup>3</sup>.

**Comment by jonathanolson** [comment]
Added units above, can you verify?

**Comment by arouinfar** [comment]
Looks great, thanks!
