### ISSUE TITLE
Update Teacher Tips for 1.1 release

### ISSUE THREAD

**Issue by arouinfar** [phetsims/density#159]
In #147 we added support for displaying the volume units in dm<sup>3</sup> and the corresponding query parameter `volumeUnits`.

We should add the Customization Options section to the Teacher Tips, and include these query parameters in the table:
* `volumeUnits`
* `screens`
* `supportsPanAndZoom`

@DianaTavares I can do this fairly quickly, so I'll take care of it. Just so you know, you can find an example of this section in the Teacher Tips [template](https://drive.google.com/drive/u/0/folders/0B6CMwxdP0NGYOURjVFZTcVZhdEE?resourcekey=0-nFsvMLWRDWr1msiAXpCqxA) in case you ever need it in the future.

**Comment by arouinfar** [comment]
Teacher Tips have been updated and uploaded to Drive.  They should be uploaded after 1.1 is published.

**Comment by DianaTavares** [comment]
The translator community is slow transiting teacher tips, but we have 8 translations of teacher tips for these simulations. It is a way to communicate to translators that they need to update teacher tips? For example, I get an email when a sim changes strings or move from prototype to a publication. Do we have the same system for teacher tips?

**Comment by arouinfar** [comment]
@DianaTavares as far as I know, there is no mechanism to let translators know when Teacher Tips are updated.

**Comment by arouinfar** [comment]
I should update the Compare Screen to include #170, so removing `status:fixed-awaiting-deploy`.

**Comment by arouinfar** [comment]
Screenshots updated, Teacher Tips ready for publication.

**Comment by arouinfar** [comment]
Teacher Tips have been updated on the website, closing.
