### ISSUE TITLE
Bug: Changing Mass doesn't change the volume of block

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/density#16]
Observed on screen 1, but could be other places. If I change the volume of a wood block, the volume changes, but if I use the mass slider, the block doesn't change size (visually). The volume slider changes, but the visual of the block isn't changing or updating.

**Comment by jonathanolson** [comment]
I believe this was fixed by the above commit.

**Comment by DianaTavares** [comment]
Yes it was! Thanks!!
