### ISSUE TITLE
Add density to perennial/data/phet-io-api-stable

### ISSUE THREAD

**Issue by arouinfar** [phetsims/density#160]
Once the PhET-iO design of sim is stable, we usually designate the sim as phet-io-api-stable. Density is missing from the list in https://bayes.colorado.edu/dev/phettest/perennial/data/phet-io-api-stable, and it should probably be added.

@jonathanolson can you take care of this? You may also want to review the checklist in https://github.com/phetsims/reactants-products-and-leftovers/issues/84 to see if anything else would apply to Density.

**Comment by jonathanolson** [comment]
Done above, can you verify?

**Comment by arouinfar** [comment]
Thanks @jonathanolson, looks good!
