### ISSUE TITLE
Unable to grab blocks through mass labels

### ISSUE THREAD

**Issue by stemilymill** [phetsims/density#163]
For https://github.com/phetsims/qa/issues/930

In 1.1.0 versions I cannot grab blocks through the mass labels. I am able to grab through the labels in the published sim and other previous versions

**Comment by jonathanolson** [comment]
Good catch! Looks like this happened when Panel in common code became pickable:true on the background by default.

Should be fixed in master, can you verify?

**Comment by stemilymill** [comment]
yes, fixed in master

**Comment by jonathanolson** [comment]
Thanks!
