### ISSUE TITLE
Autoselect doesn't work on scale

### ISSUE THREAD

**Issue by stemilymill** [phetsims/density#166]
For https://github.com/phetsims/qa/issues/930

Autoselect studio feature holding `opt/alt` or `ctrl` while hovering over the scale in the Mystery screen does not work. The scale is a featured element, but I still checked without being filtered on featured and no change. Autoselect seems to work for all other elements.

**Comment by arouinfar** [comment]
That seems reasonable to me @jonathanolson. We don't want/need touch interaction for the scales in Density. Let's close.

Buoyancy has movable scales, and I confirmed that they are can be autoselected in Studio.
