### ISSUE TITLE
Possible for blocksRadioButtonGroup to be very close to Reset All button

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/density#168]
**Test device**
MacBook Air M1 chip

**Operating System**
13.3.1

**Browser**
Safari 

**Problem description**
For https://github.com/phetsims/qa/issues/930, in Studio on the Intro Screen:
The `massNumberControl.visibleProperty` and `volumeNumberControl.visibleProperty` are PhET-iO featured. Setting both properties to false for Block A causes the `blocksRadioButtonGroup` to shift right in order to stay aligned with the Block A control panel. 

**Steps to reproduce**
1. In studio set `view.blockAControlPanel.massNumberControl.visibleProperty` to false
2. Set `view.blockAControlPanel.volumeNumberControl.visibleProperty` to false

EDIT: 
This also happens if I set `massNumberControl.slider.visibleProperty` and `volumeNumberControl.slider.visibleProperty` to false instead of the steps above. 

**Visuals**
<img width="546" alt="Screenshot 2023-04-26 at 1 29 59 PM" src="https://user-images.githubusercontent.com/87318828/234656000-98b0c563-181d-45b8-b177-d33ccb749e38.png">

**Comment by Nancy-Salpepi** [comment]
In some locales (ex. Ku, Bo) in can look like this:
<img width="319" alt="Screenshot 2023-04-26 at 1 39 20 PM" src="https://user-images.githubusercontent.com/87318828/234658976-d4ada90d-afad-48a1-b6c4-0891f0dc6604.png">

**Comment by jonathanolson** [comment]
This looks like a consequence of the constraints (keep the button group bottom-aligned with the bottom of the pool, left-aligned with the upper-right content). @arouinfar or @DianaTavares, thoughts on if anything should be done about this?

**Comment by arouinfar** [comment]
How about we remove the requirement to keep it left-aligned with the Blocks panel? Since the buttons are in close proximity to the pool, and the pool size shouldn't change, it seems safer to maintain bottom-alignment with the pool. Here's what it would look like with a narrow Blocks Panel:

![image](https://user-images.githubusercontent.com/8419308/236902802-229c5272-4f75-43ca-bf1b-017742a58d1c.png)

@DianaTavares does that seem reasonable to you?

**Comment by DianaTavares** [comment]
Yes, it is better if the blocksRadioButtonsGroup are not aligned with the up panel. Less movement if they are only in alignment with the pool

**Comment by jonathanolson** [comment]
Implemented in master, how this this look/feel?

**Comment by arouinfar** [comment]
Looks great, thanks @jonathanolson!
