### ISSUE TITLE
Block on scale changes mass when clicked

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/density#169]
**Test device**
Samsung
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/930. Also seen in published.
When a block is sitting on the scale and you click it to pick it up, the mass read may change. It may change only .01 kg or it may change .3 kg or more. It tends to get "heavier." The amount is fairly consistent for each block, and this was mound with a mouse, so I don't think it is me accidentally moving the block. @Nancy-Salpepi also saw this, so it doesn't seem to be dependent on device.

**Visuals**

https://user-images.githubusercontent.com/41024075/234670216-ad469538-cebe-40e4-9c4e-76228ba1da7a.mp4

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Density‬
URL: https://phet-dev.colorado.edu/html/density/1.1.0-dev.3/phet/density_all_phet.html
Version: 1.1.0-dev.3 2023-04-19 18:32:51 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/112.0
Language: en-US
Window: 1536x731
Pixel Ratio: 1.25/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (ANGLE (Intel, Intel(R) HD Graphics Direct3D11 vs_5_0 ps_5_0))
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by arouinfar** [comment]
Thanks @KatieWoe.

It seems like the block is moving ever-so-slightly when grabbed which is causing the mass display to change. I think the behavior is acceptable, but I think it would be good for @jonathanolson to confirm things are working as expected.

**Comment by jonathanolson** [comment]
This seems like an unfortunate side-effect of how we handle mouse/touch interaction. So expected, and I don't see an easy way to work around it (but it may be possible).

**Comment by arouinfar** [comment]
Thanks @jonathanolson. Good to know this is the expected behavior, no workaround is necessary. Let's close.
