### ISSUE TITLE
Bug: Density of 1 kg/L block pops off the bottom

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/density#17]
The physics of the 1 kg/L block is not quite right. It should sit whereever you put it in the water, but right now, if you try to place it on or near the bottom of the pool, it repels the bottom when you let go and settles a little bit above the bottom. I'm not understanding what physics is leading to this behavior, but it should just sit on the bottom if it is placed there. If there is some upward force from the poll bottom, please set that to zero upon release so that the block stays put and does not experience acceleration.

**Comment by jonathanolson** [comment]
I'm exploring solutions to this, essentially the physics engine allows a bit of "slop" where things can overlap slightly (so the block is being pushed INTO the ground, and when released experiences a repulsion force).

**Comment by DianaTavares** [comment]
The behavior of the block and the walls of the pool is the same that the other blocks use to have with the "transparent walls" that restrict the block in the play area (issue #12):

> if the user moves fast the block against the invisible wall, it jumps a lot. Can the collision between the wall and the block be inelastic? 
> ![jumpingBlock](https://user-images.githubusercontent.com/26031501/80020452-ad92ce00-849e-11ea-8245-91ca5389241d.gif)

You can see also the rebound of the blocks in all the walls of the pool with all the blocks, but with the block that have 1 kg/L density this behavior looks like "repulsion". 
@jonathanolson, can the collision between the blocks and the walls of the pool be inelastic?

**Comment by jonathanolson** [comment]
I believe I've finally figured out a good way to handle things like this, the behavior is looking much better to me in master. Can you verify?

**Comment by DianaTavares** [comment]
It looks perfect to me!
