### ISSUE TITLE
User suggestion: Add labels to Compare blocks

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/density#170]
> I have a student that is color blind. When looking to use 'Compare' on density, he had no way of distinguishing the blocks from each other as they were not labeled except by color.
> 
> For the Mystery simulation, they are very clearly labeled. The Compare simulation is the one that does not have labels on the blocks. Only a colored block with a mass on it. I was just suggesting that an A, B, C, D on the compare simulation might be beneficial for those students that are color blind.

**Comment by DianaTavares** [comment]
I agree with the user. @jonathanolson, this is something that can be added in this release of Density? Add A, B C, and D labels to the blocks to the Compare screen.

**Comment by jonathanolson** [comment]
Yes, this should be doable pretty easily!

**Comment by jonathanolson** [comment]
Added the labels in master, can you see how they look?

Also, the blocks in the three scenes are labeled ABCD left-to-right. This means the colors on the blocks have different labels on the same-volume one, due to the configuration of the level. @arouinfar and @DianaTavares, is that acceptable?

**Comment by arouinfar** [comment]
> Also, the blocks in the three scenes are labeled ABCD left-to-right. This means the colors on the blocks have different labels on the same-volume one, due to the configuration of the level.

Looks good in master @jonathanolson. 

I reviewed in Studio, and things generally look good, but it would be nice to see a linked `nameProperty` under the Compare blocks as we have for the Mystery blocks. Is that something that you could add @jonathanolson?

**Comment by jonathanolson** [comment]
<img width="990" alt="image" src="https://user-images.githubusercontent.com/480878/236956143-2aefbd76-4175-4e85-9233-80c6194ef362.png">

I'm seeing a linked nameProperty for these. Are there cases where it's not working? (I checked all the compare blocks, and they seem to have it).

**Comment by arouinfar** [comment]
Thanks @jonathanolson. I'm also seeing a linked `nameProperty`. Not sure why I missed it yesterday, but looks good now!

Not sure if this should be closed, or tagged as an issue for QA in the next cycle, so back to you.
