### ISSUE TITLE
What is the expected behavior of ?webgl=false

### ISSUE THREAD

**Issue by zepumph** [phetsims/density#171]
@jonathanolson and I were surprised to see some webgl-like content when running both with `?webgl=false` and when turing off "hardware acceleration" in Chrome:

![image](https://user-images.githubusercontent.com/6856943/235724911-af810e96-1049-40cb-9aa1-b1959e85992e.png)

**Comment by jonathanolson** [comment]
After https://github.com/phetsims/density-buoyancy-common/commit/08c116f2, we're creating the full view (with WebGL if it's somehow possible) even with `?webgl=false` or if webgl isn't running. This is so we can have the same phet-io API.

@zepumph any objections to how that is happening? It does look a bit weird in this case, but I don't see a way to prevent it easily.

**Comment by zepumph** [comment]
No worries. I remember we were confused and wanted to make sure things weren't a bug. Ready to close?
