### ISSUE TITLE
Block can blend in to background

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/density#176]
**Test device**
Samsung
**Operating System**
Win 11
**Browser**
Firefox
**Problem description**
For https://github.com/phetsims/qa/issues/942.
At a certain density the custom block can blend in pretty perfectly with the background of the pool. This is both above and bellow the water line, though the density has the block pretty high in the water. This is the same in published.
**Steps to reproduce**
1. Set a block to custom on the first screen.
2. Set mass to .5 kg and volume to 5 L

**Visuals**
![camo](https://github.com/phetsims/density/assets/41024075/8fcf4e64-43c1-4fff-a8c4-9b3d225a0d93)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Density‬
URL: https://phet-dev.colorado.edu/html/density/1.1.0-rc.1/phet/density_all_phet.html
Version: 1.1.0-rc.1 2023-05-11 11:14:15 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/113.0
Language: en-US
Window: 1536x731
Pixel Ratio: 1.25/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (ANGLE (Intel, Intel(R) HD Graphics Direct3D11 vs_5_0 ps_5_0))
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by DianaTavares** [comment]
I test some colors in [the Color-editor tool](https://bayes.colorado.edu/dev/phettest/phetmarks/color-editor.html?sim=density&brand=phet), test color blindness and I found this color perfect to distinguish the back of the pool from the block `#B79F9F`:  

![image](https://github.com/phetsims/density/assets/26031501/0e949b9c-dea6-45ad-a539-a9efb33a8c75)

Can you update it @jonathanolson ?

**Comment by jonathanolson** [comment]
Patched above and in the branch. @DianaTavares does this look good?

**Comment by DianaTavares** [comment]
Perfect! Thanks!!

**Comment by Nancy-Salpepi** [comment]
This looks good in rc.2
