### ISSUE TITLE
Scale can be partially off-screen when launched from studio

### ISSUE THREAD

**Issue by stemilymill** [phetsims/density#177]
For https://github.com/phetsims/qa/issues/942.

If I launch from studio and then resize the window to be more narrow while the page is loading, the scale can be partially off-screen. It will stay in that position if reset all is clicked. I did not see this happen with the phet brand sim.

https://github.com/phetsims/density/assets/85511101/9e6a9400-263c-41be-9622-2ee59374a874

The video shows the sim launching already in mystery screen, but the same thing happens regardless of launched state- when I go to the mystery screen the scale location is incorrect.

Perhaps relevant https://github.com/phetsims/density-buoyancy-common/issues/67.

**Comment by jonathanolson** [comment]
@arouinfar do we want people with phet-io to be able to customize the location of the scale? Here, we're setting a different phet-io state that moves the scale. I could have phet-io NOT able to change the scale location (it seems really tricky how to handle phet-io state that depends on the sim aspect ratio).

Thoughts?

**Comment by arouinfar** [comment]
@jonathanolson I don't think we need to allow customization of the scale's position. The documentation already cautions clients to be mindful of the aspect ratio when making customizations, and this feels like an edge case. I'm inclined to do nothing here. If that seems reasonable @jonathanolson, we can close this as wont-fix.

**Comment by jonathanolson** [comment]
Seems reasonable, marking as wont-fix.
