### ISSUE TITLE
Some strings don't stay translated when switching units

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/density#178]
**Test device**
Samsung
**Operating System**
Win 11
**Browser**
Firefox
**Problem description**
For https://github.com/phetsims/qa/issues/942. 
When the Units for volume are switched to dm^3 other strings that were translated may appear untranslated. In the density accordion box the word Density and the unit kg will appear in English even if they are translated when using L as the units
**Steps to reproduce**
1. Go to the first screen
2. Change the language to one that translates both "Density" and "kg". Tajik is what I used
3. Observe the Density accordion box
4. Change the units to dm^3
5. Observe the Density accordion box

**Visuals**
![L](https://github.com/phetsims/density/assets/41024075/23b40b42-f1b4-4751-af73-e93004894728)
![dm3](https://github.com/phetsims/density/assets/41024075/126f8510-cc61-419f-b682-cb2118aa13bb)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Зиччӣ‬
URL: https://phet-dev.colorado.edu/html/density/1.1.0-rc.1/phet/density_all_phet.html
Version: 1.1.0-rc.1 2023-05-11 11:14:15 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/113.0
Language: en-US
Window: 1536x731
Pixel Ratio: 1.25/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (ANGLE (Intel, Intel(R) HD Graphics Direct3D11 vs_5_0 ps_5_0))
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by jonathanolson** [comment]
This looks like a case where the translation doesn't have translated strings for NEW yet-unpublished strings (e.g. densityReadoutDecimetersCubed).

Because it doesn't have these strings yet, it falls back to English.

@arouinfar since we're adding strings for this publication, should we be notifying translators? Is there anything for me to do here?

**Comment by arouinfar** [comment]
Thanks @KatieWoe. 

@jonathanolson we have the ability to send notifications out to translators through the website, so we can notify them after Density is republished.

I opened #183 to notify translators, so I don't think there's anything else to do here, closing.
