### ISSUE TITLE
Volume units in Preferences menu are not aligned

### ISSUE THREAD

**Issue by stemilymill** [phetsims/density#179]
For https://github.com/phetsims/qa/issues/942.

In the volume units control in the preferences menu, the dm<sup>3</sup> is lower than the other text. 

I cropped this screenshot to the bottom edge of dm<sup>3</sup> to clearly show it.  

![preferences menu dm3 lower than other text](https://github.com/phetsims/density/assets/85511101/9413a5c8-2980-41dd-9a7a-bad2b25013e1)

**Comment by arouinfar** [comment]
Thanks @stemilymill. It looks like the radio button labels are vertically centered. The exponent adds height to the label, so everything is shifted down a bit to remain centered. I don't think we need to do anything here, closing.
