### ISSUE TITLE
Bug: the density readout for the blue block disappears when the density is 10

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/density#18]
the density readout for the blue block disappears when the density is 10 kg/L

9.9 kg/L is shown in the sim
![image](https://user-images.githubusercontent.com/26031501/82938050-d2bfa400-9f56-11ea-9c53-26e061bea14d.png)

But exactly 10 kg/L is not
![image](https://user-images.githubusercontent.com/26031501/82938098-e79c3780-9f56-11ea-8830-b13fcdfe3fd2.png)

**Comment by jonathanolson** [comment]
Should be fixed in master.
