### ISSUE TITLE
Flickering in State wrapper on Chromebook

### ISSUE THREAD

**Issue by stemilymill** [phetsims/density#181]
For https://github.com/phetsims/qa/issues/942

Seen on Chromebook (Lenovo 100e Chromebook 2nd gen MTK) ChromeOS Version 113.0.5672.134 (Official Build) (32-bit)

I do not see this on another chromebook I borrowed so it might be device-specific (this chromebook has had several)

Multiple parts are flickering in the state wrapper. This is happening in both the upstream and downstream copies. I see this in a brand new incognito window as well.

[density state wrapper wild flickering.webm](https://github.com/phetsims/density/assets/85511101/8a24e427-f795-429b-8283-882ff5e56e25)

(you can also see how blurry the blocks are but i'm sure that's unrelated)

**Comment by arouinfar** [comment]
@jonathanolson I don't think it's important for the state wrapper to work well on the Chromebook. However, I think we want the state captured from a Chromebook to be accurate. It's not clear to me if this flickering indicates issues with capturing the state on Chromebook or not.

**Comment by arouinfar** [comment]
> This looks like it's just a visual issue, doesn't look like it's causing incorrectness. Thoughts?

Agreed @jonathanolson. I don't think we need to do anything here, so let's close.
