### ISSUE TITLE
View and Linked element seem odd on water volume indicator

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/density#182]
**Device**
MacBook Pro
**OS**
MacOS 13.4
**Browser**
Chrome
**Problem Description**
For https://github.com/phetsims/qa/issues/942.
In Studio, when using Opt/Alt to look at the View Element of the water volume label, it will be `density.introScreen.view` and when looking at the Linked Element with Ctrl it will be `density.general.model.strings.density.screen.introStringProperty`. These seem odd choices to me.
**Visuals**

https://github.com/phetsims/density/assets/41024075/667ffd10-034a-4e9b-900d-7aaad67bf3e5

**Comment by arouinfar** [comment]
Good find @KatieWoe. I'm surprised that autoselect does anything at all with that readout since it doesn't have any explicit instrumentation in the tree. With opt/alt it takes you to the view of whatever screen you're on, which seems fine. I'm not sure why using ctrl would take you to the screen name, since these aren't linked.

**Comment by jonathanolson** [comment]
Should I make it pickable:false, so that the label doesn't autoselect anything?

**Comment by jonathanolson** [comment]
Hmm, perhaps it might be necessary for me to discuss how autoselect works. It's not just the volume indicator, it's also a large amount of the background of the sim that the autoselect triggers the view on (it's somewhat how we do drags).

Effectively, pickable:false doesn't do much. Should I work with phet-io developers to figure out a solution?

**Comment by arouinfar** [comment]
> It's not just the volume indicator, it's also a large amount of the background of the sim that the autoselect triggers the view on (it's somewhat how we do drags).

Strange, when I use autoselect in Chrome and Safari, I don't get any hits for the sim background, in general. The only background-like thing that appears autoselectable is the pool's volume indicator. While I find it a little bit odd that `ctrl` will select the screen name, I don't think it's terribly harmful. I'm okay with leaving this alone @jonathanolson.
