### ISSUE TITLE
Bug: crushing spliced blocks generates strange behavior

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/density#19]
When several blocks placed on the top of each other are crushed (a downward force is generated with the mouse), in some situations they have a very strange of overlapping and jumping (see the next gif):

![Untitled](https://user-images.githubusercontent.com/26031501/83047895-a6675e80-a00e-11ea-8dd5-819f7c0a2c83.gif)

 Not all the configurations of blocks placed on the top of others generate that behavior. The next gif shows that block A and B generate the strange behavior, but when block D is placed in the top of them and is pushed, no strange behavior is presented: 

![Untitled2](https://user-images.githubusercontent.com/26031501/83048572-681e6f00-a00f-11ea-940f-9744938e372b.gif)

In the beginning, I thought that the problem was presented in specific blocks size, but now I think that it is in specific densities. I will continue playing to discover what can be the problem.

**Comment by DianaTavares** [comment]
After playing more with the blocks, the strange overlapping /bumping behavior is related to the mass of the objects. More mass, more strange behavior.  The next picture show the overlapping of blocks with different mass with the ground when the block is pushed down with the mouse (yellow block has m=65.3 kg) : 

![image](https://user-images.githubusercontent.com/26031501/83056260-b422e100-a01a-11ea-9ab0-fa43d28f6137.png)

When the block with more mass is placed in the top of a pile of blocks,  and I push down with the mouse, the blocks overlap, especially the ones with less mass: 

![image](https://user-images.githubusercontent.com/26031501/83056804-9f931880-a01b-11ea-8186-c4acae5f9bf6.png)

The suppression of heavy blocks on light blocks happens on all screens. This is an example on screen 1 with the lightest block that can be created (m = 0.1) and the aluminum with the maximum mass (m = 27)

![Untitled3](https://user-images.githubusercontent.com/26031501/83057447-85a60580-a01c-11ea-8683-c438452054d5.gif)

Pushing a block down with the mouse in the ground or over other blocks (when they are in the ground or in the bottom of the pool)  should not generate any effect (as happens with the Flash simulation). They should be rigid and not go into each other. 

Ideas of how to solve this?

**Comment by jonathanolson** [comment]
I believe I've finally figured out a good way to handle things like this, the behavior is looking much better to me in master. Can you verify?

**Comment by DianaTavares** [comment]
Yes, it looks better! The blocks still overlap, but less than the last time:

![Screen Shot 2020-06-02 at 12 50 22 PM (2)](https://user-images.githubusercontent.com/26031501/83552841-0149fb80-a4d0-11ea-827d-981fdb5a8a96.png)
![Screen Shot 2020-06-02 at 12 51 19 PM (2)](https://user-images.githubusercontent.com/26031501/83552845-0313bf00-a4d0-11ea-82e2-fd7e7306bf35.png)

**Comment by jonathanolson** [comment]
I can't reproduce that locally. Can you try https://phet-dev.colorado.edu/html/density/1.0.0-dev.10/phet/density_en_phet.html (just deployed) and if it happens, give me reproduction steps?

**Comment by DianaTavares** [comment]
In that link, I see the same behavior.
The steps are:
1) Activate the B block
2) Change the volume of the B block to V=10L
3) Change the A Block to Custom and modify it mass to 0.1 kg and in volume to 10L
4) Put A block in the ground outside the pool and the B block at the top of A block. That already shows a little overlap between A block and the ground:

![Screen Shot 2020-06-02 at 1 36 27 PM](https://user-images.githubusercontent.com/26031501/83556780-1de93200-a4d6-11ea-973e-dc63e033b097.png)

5)With the mouse, push the B Block down: 
![83552841-0149fb80-a4d0-11ea-827d-981fdb5a8a96](https://user-images.githubusercontent.com/26031501/83556879-440ed200-a4d6-11ea-9fec-37a305c65e04.png)

Also, If Block A (The block with less mass) is at the top of block B, I can lift both blocks if I move block B up.
![Screen Shot 2020-06-02 at 1 40 19 PM (2)](https://user-images.githubusercontent.com/26031501/83557116-b1bafe00-a4d6-11ea-88aa-3119d82252a6.png)

But if it is the other way, the heavy block (B) on the light block (A), block A cannot be moved up, and it is hard to move it left-right. It is like a big friction force only because the heaviest block is at the top.  I am not sure if this information is relevant to the issue.

We can ask @KatieWoe  to review in other computers. You know that it is not the first time that my computer has a strange sim performance that is a computer-specific issue.

**Comment by jonathanolson** [comment]
It's likely not computer-specific, investigating.

**Comment by jonathanolson** [comment]
The following code will reproduce when all screens are enabled:
```js
const model = phet.joist.sim.screens[1].model
model.secondaryMassVisibleProperty.value = true;
model.secondaryMass.updateSize( phet.densityBuoyancyCommon.Cuboid.boundsFromVolume( 0.01 ) );
model.primaryMass.updateSize( phet.densityBuoyancyCommon.Cuboid.boundsFromVolume( 0.01 ) );
model.primaryMass.materialProperty.value = phet.densityBuoyancyCommon.Material.createCustomSolidMaterial( { density: 10 } );
model.primaryMass.matrix.set02( -0.5451005935668946 );
model.primaryMass.matrix.set12( 0.10672173500061036 );
model.primaryMass.writeData();
model.secondaryMass.matrix.set02( -0.5815437316894532 );
model.secondaryMass.matrix.set12( 0.36697516441345214 );
model.secondaryMass.writeData();
```

**Comment by jonathanolson** [comment]
For fine-tuning the physics, I thought it would be more helpful to expose the parameters that I currently have available as query parameters, so that a better balance could be found.

I've added the following query parameters:
```js

  // Length (in seconds) of each internal p2 timestep. Ran into weird behavior when we had only 60 a second.
  p2FixedTimeStep: {
    type: 'number',
    defaultValue: 1 / 120
  },

  // Controls the maximum number of physics substeps in a single step. Usually not reached
  p2MaxSubSteps: {
    type: 'number',
    defaultValue: 30
  },

  // We multiply our model sizes (width/height, etc.) by this amount before it is sent to the physics engine, so the
  // engine thinks things are this-much-bigger.
  p2SizeScale: {
    type: 'number',
    defaultValue: 5
  },

  // We multiply our mass amounts by this amount before it is sent to the physics engine, so the engine thinks things
  // are this-much-more-massive
  p2MassScale: {
    type: 'number',
    defaultValue: 0.1
  },

  // Default (maximum) number of main iterations per step to run before reaching the tolerance
  p2Iterations: {
    type: 'number',
    defaultValue: 40
  },

  // Amount of iterations used to compute friction
  p2FrictionIterations: {
    type: 'number',
    defaultValue: 10
  },

  // When the amount of error goes below this amount, further iterations are not done
  p2Tolerance: {
    type: 'number',
    defaultValue: 1e-10
  },

  // How "bouncy" things are supposed to be (0-1 generally)
  p2Restitution: {
    type: 'number',
    defaultValue: 0
  },

  // An amount of force applied to all pointer-mass interactions (e.g. when you grab it with the mouse)
  p2PointerBaseForce: {
    type: 'number',
    defaultValue: 0
  },

  // Adds to the amount of force applied to all pointer-mass interactions (e.g. when you grab it with the mouse), but
  // is this value TIMES the mass's mass value.
  p2PointerMassForce: {
    type: 'number',
    defaultValue: 5000
  },

  // Stiffness:
  // "Hardness of the contact. Less stiffness will make the objects penetrate more, and will make the contact act more
  // like a spring than a contact force." - p2 default is 1e6
  // Can be increased, but can make things unstable or bouncy.

  // Stiffness to use for ground-mass interactions
  p2GroundStiffness: {
    type: 'number',
    defaultValue: 1e6
  },

  // Stiffness to use for barrier-mass interactions
  p2BarrierStiffness: {
    type: 'number',
    defaultValue: 1e6
  },

  // Stiffness to use for mass-mass interactions
  p2DynamicStiffness: {
    type: 'number',
    defaultValue: 1e6
  },

  // Relaxation:
  // "The number of time steps needed to stabilize the constraint equation. Typically between 3 and 5 time steps."
  // p2 default is 4.

  // Relaxation to use for ground-mass interactions
  p2GroundRelaxation: {
    type: 'number',
    defaultValue: 1 // reduction results in less ground penetration when a mass is sitting on the ground
  },

  // Relaxation to use for barrier-mass interactions
  p2BarrierRelaxation: {
    type: 'number',
    defaultValue: 4
  },

  // Relaxation to use for mass-mass interactions
  p2DynamicRelaxation: {
    type: 'number',
    defaultValue: 4
  }
```

The latest improvements were made by dropping the equivalent of p2MassScale from 1 to 0.1, but I'm having trouble finding the ideal combinations of these. @DianaTavares, would you be able to experiment with these to see if you can find a better combination of parameters that doesn't run into this issue?

**Comment by jonathanolson** [comment]
For instance, running with `?p2DynamicRelaxation=0.5` would adjust that parameter, and multiple ones can be combined like `?p2DynamicRelaxation=0.5&p2GroundRelaxation=100`

**Comment by jonathanolson** [comment]
To help reproduce the existing case, typing the code in https://github.com/phetsims/density/issues/19#issuecomment-637802881 into the console should set it into that configuration. Optionally if you additionally pass the `screens=1` query parameter (it loads a bit faster), you would need to change the `[1]` on the first line to `[0]`. That helped for speeding up testing for me.

If you need any assistance with this, please let me know.

**Comment by DianaTavares** [comment]
I understand that the actions that I need to do are: going to the PhET test and play with the Query parameter in https://github.com/phetsims/density/issues/19#issuecomment-637817008 modifying the values until I get more appropriate physics behavior in the simulation. right? 

But there are 16 different Query parameters, and they can be combined. Also, I am not sure what is the range of each parameter. I am not very sure how to start.

**Comment by DianaTavares** [comment]
I have been playing a lot with the Query parameters an I don't have a solution yet. 
I am just summarizing some of my reflections: 

I already try all the variables and none of them improve this behavior: A little overlapping between the ground and the 0.10kg block when the aluminum block is placed in the top
![image](https://user-images.githubusercontent.com/26031501/83814831-a7d6fd80-a684-11ea-999b-86ed8d70a768.png)

It is an issue related to the mass variable because even that the block is small we can see that overlapping
![image](https://user-images.githubusercontent.com/26031501/83814989-f5536a80-a684-11ea-95aa-15fe1d926aae.png)

This behavior disappears if the mass of the block is over 0.5 kg
![image](https://user-images.githubusercontent.com/26031501/83815245-6430c380-a685-11ea-8324-1ad0966564bb.png)

It is not really a solution, but we can have **the min mass in the custom option of 0.5 kg.** The minimus density in the sim is going to be 0.05 kg/L, lower than the Styrofoam. Now, Styrofoam needs a min mass of 0.15, but the block is so small that the mass label hides that strange overlapping when another block is at the top.  

Now, regarding the problem that the block is submerged in the ground when another block on it is pressed down, I have already identified 4 variables that affect that behavior. I keep playing with them to find the best combination
![image](https://user-images.githubusercontent.com/26031501/83815705-6c3d3300-a686-11ea-8bf5-814ad9211612.png)

**Comment by DianaTavares** [comment]
the query parameter that helps to improve this behavior was p2FrictionIterations. The default value was 10. I changed several times with an acceptable result when the value is 3500

http://phettest.colorado.edu/density/density_en.html?ea&brand=phet&p2FrictionIterations=3500

The next gif is with the last link. As you can see, when the heaviest blocks are on top of the lightest blocks, and with the mouse, a dow force is generated, the overlapping now is smaller. The FrictionInteractions can be bigger to reduce this behavior even more, but the blocks move slower in the sim (that is also appreciable in the gif). 

![Density](https://user-images.githubusercontent.com/26031501/84184802-9d857c80-aa53-11ea-9d19-754f9dc474de.gif).

I also played with the query parameters p2PointerMassForce (default value=5000), and p2PointerBaseMass (default value=0). MassForce multiply the force by the mass of the object, giving more force to the massive blocks. In the sim then you can put a lot of blocks over massive blocks and move the massive block with all the other blocks in its top. But when a massive block is over a lighter block, it can be moved.

![density2](https://user-images.githubusercontent.com/26031501/84186741-9318b200-aa56-11ea-8289-2b63b67463a3.gif)

 I am not sure if we want that behavior in the sim. I think that it is better if students can move any block with other blocks at the top. This is an example of how the sim can be modified:
http://phettest.colorado.edu/density/density_en.html?ea&brand=phet&p2FrictionIterations=3500&p2PointerMassForce=0&p2PointerBaseForce=9000

But the Mistery Screen is very slow.

**Comment by KatieWoe** [comment]
Spliced blocks still occurring in https://github.com/phetsims/QA/issues/507
![overlappingblocks](https://user-images.githubusercontent.com/41024075/84933640-705c4e00-b093-11ea-826f-391c2cf1697a.gif)

**Comment by KatieWoe** [comment]
This also seems to have an odd effect on the scale and how much mass it reads if this is done on top of the scale.
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/41024075/86978710-bfe6e480-c13c-11ea-9540-2b58878f3610.gif)

**Comment by DianaTavares** [comment]
In the version: https://phet-dev.colorado.edu/html/density/1.0.0-dev.15/phet/density_en_phet.html
When several blocks placed on top of each other are crushed (a downward force is generated with the mouse), I don't see any stage behavior (yeah!!) 

The problem is when blocks are pushed against the wall of the pool. It merges a little bit, and if the block is small and with less mass, it can go throw the wall:

https://user-images.githubusercontent.com/26031501/112072418-64784d80-8b37-11eb-88ef-51b01e0c79f5.mov

**Comment by DianaTavares** [comment]
this issue has been a long discussion of different, but related, strange behaviors. the only one stage behavior that remains is reported in issue #53. I am closing this issue to better focus the attention on the remaining thing to solve the blocks going throw the walls of the pool.
