### ISSUE TITLE
Improve the appearance of the edges in the sim

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/density#20]
The edges of the blick and the pool walls aren't straight lines. Can the edges be improved? 

![image](https://user-images.githubusercontent.com/26031501/83051129-2c85a400-a013-11ea-91f3-19f96f2514ef.png)

**Comment by jonathanolson** [comment]
Possibly, can you provide the information in the Phet Menu from "Report a Problem..." popup?

This might be computer-specific, I'm specifying `antialias: true` to three.js, but that may not be handled on your browser.

For context, this is how things appear on my side (properly antialiased):

<img width="248" alt="Screen Shot 2020-05-27 at 5 18 06 PM" src="https://user-images.githubusercontent.com/480878/83081631-5d2f0300-a03e-11ea-82f4-29a20f2267ac.png">

**Comment by DianaTavares** [comment]
It is not the first time that I get and computer-specific issue. I always use Chrome as a Browser. I already review Firefox and Safari on my computer and the edges in the sim look great. 

Probably test it in some other MacBook on Chrome, and if the edges look good there, just close this issue. I ask @KatieWoe to review it!

Here is the "Report a Problem" information

**Test device**
MacBook Air (13-inch, 2017)
![image](https://user-images.githubusercontent.com/26031501/83161701-62d42980-a0ce-11ea-8996-28cbece400b3.png)


**Operating System**
macOS Majove version 10.14.6

**Browser**
Google Chrome Version 81.0.04044.138

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Density‬
URL: http://phet.colorado.edu/sims/html/density/latest/density_en.html
Version: 1.0.0-dev.9 2020-05-08 14:46:54 UTC
Features missing: generatedcontent, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
Language: es-419
Window: 1567x942
Pixel Ratio: 0.8999999761581421/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

**Comment by KatieWoe** [comment]
I checked a few platforms and did not see anything to the degree that @DianaTavares did myself. If I got really close and squinted, I could sometimes see unevenness or white spots, but nothing too obvious. Checked the prototype version on the website.
Side note: it doesn't load on IE.

**Comment by DianaTavares** [comment]
Then it is a computer-specific issue. Thanks, @KatieWoe. Closing!!

**Comment by KatieWoe** [comment]
I will keep an eye out for this when we get to more in depth testing (rc-tests etc.)
