### ISSUE TITLE
Density Polishing

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/density#23]
I'm curious about what should be polished for Density. I recall preferences being to remove more of the dynamic reflections (but potentially still leave some, e.g. especially for ice). Switching to one environment map could also save performance.

So in general, I'd like to know about what minor changes should be done (any general physics-like behavior comments should go in https://github.com/phetsims/density/issues/19, the rest here).

https://phet-dev.colorado.edu/html/density/1.0.0-dev.11/phet/density_all_phet.html is the latest dev link

**Comment by arouinfar** [comment]
> I recall preferences being to remove more of the dynamic reflections (but potentially still leave some, e.g. especially for ice).

@jonathanolson I think the blocks and scale are too reflective. Cutting down on the dynamic reflections would look nice, and I would even tone it down for ice too. 
![image](https://user-images.githubusercontent.com/8419308/83677781-e479fa80-a599-11ea-8302-4165ed01df6a.png)

**Comment by DianaTavares** [comment]
I agree with @arouinfar comments.

**Comment by jonathanolson** [comment]
@arouinfar and @DianaTavares, is there anything left to be done with the current master here?

**Comment by arouinfar** [comment]
Master is looking good to me @jonathanolson.

**Comment by DianaTavares** [comment]
Also for me, it looks good. Thanks @jonathanolson
