### ISSUE TITLE
Should a new set be generated each time you switch to random?

### ISSUE THREAD

**Issue by muedli** [phetsims/density#25]
For https://github.com/phetsims/QA/issues/507.

Suppose you're playing with a set of random blocks in the mystery screen. Then you decide to switch to set 3. When you're done with set 3, you want to go back to your set of random blocks. Unfortunately, the set of random blocks you were playing with earlier is gone because a new set is generated each time you switch the radio button to the random set. Should a new set be generated each time you switch to random?

**Comment by DianaTavares** [comment]
You are right, it shouldn't. I also think that save the state of the scenes can be useful in the mystery screen. I have been playing with the different sets and it's uncomfortable that I placed the blocks in a specific configuration, and when I change to another set, the position of the blocks is lost. 
@jonathanolson  and @ariel-phet 
Does it take a lot of work to allow the simulation not to change blocks in the random section until the refresh button is activated?
Can also the position of the blocks in the different scenes sets be saved?

**Comment by ariel-phet** [comment]
@DianaTavares @muedli 

Agreed, especially since there is a "generate new random set" button, the random set should remain constant until that button is pressed. Changing sets should not affect the random set of blocks chosen.

**Comment by jonathanolson** [comment]
Implemented above, can you verify it works as expected/desired?

**Comment by DianaTavares** [comment]
It works perfectly! Thanks
