### ISSUE TITLE
In “Mystery” screen, 1A has density of 3.53 but diamond reports as 3.51 in the table

### ISSUE THREAD

**Issue by samreid** [phetsims/density#28]
In “Mystery” screen, 1A has density of 3.53 but diamond reports as 3.51, is that by design?

**Comment by jonathanolson** [comment]
That is correct according to the design in https://github.com/phetsims/density/issues/6. @DianaTavares should anything be tweaked here?

**Comment by DianaTavares** [comment]
My mistake, sorry. The mass of that block should be 3.51 kg, in order to have the right density. @jonathanolson, please modify the mass of 1A block.

**Comment by jonathanolson** [comment]
Implemented above. If there are other blocks that should have the same density as a reference, can you let me know so I can reference it in the code?

**Comment by DianaTavares** [comment]
I already review all the values and the values of the blocks that have an issue are reported in #27
