### ISSUE TITLE
IE failure to load

### ISSUE THREAD

**Issue by loganbraywork** [phetsims/density#29]
**Test device**

Windows 10 Laptop

**Operating System**

Windows 10 v. 1903

**Browser**

Internet Explorer v.11.900.18362.0

**Problem description**

For https://github.com/phetsims/QA/issues/507

IE fails to load entirely. Since IE is no longer a supported browser, assigning ariel to decide the fate of this issue. I will note that the sim claims that WebGL is not available or enabled, but IE 11 and up has WebGL enabled by default. Also appears broken on Katie's device as well.

**Visuals**

![2020-06-15WebGLnotenabledorAvailableDensity](https://user-images.githubusercontent.com/54685448/84699067-1ed68680-af0e-11ea-9740-75778057fc48.PNG)

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
  
Name: ‪Density‬

URL: https://phet-dev.colorado.edu/html/density/1.0.0-dev.11/phet/density_all_phet.html

Version: 1.0.0-dev.11 2020-06-03 18:06:51 UTC

Features missing: touch, fullscreen

Flags: pointerEnabled, msPointerEnabled, pixelRatioScaling

User Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Zoom 3.6.0; rv:11.0) like Gecko

Language: en-US

Window: 1574x773

Pixel Ratio: 1.2200000286102295/1

WebGL: WebGL 0.94

GLSL: WebGL GLSL ES 0.94

Vendor: Microsoft (Internet Explorer)

Vertex: attribs: 16 varying: 15 uniform: 512

Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)

Max viewport: 16384x16384

OES_texture_float: true

Dependencies JSON: {}

**Comment by ariel-phet** [comment]
@jonathanolson I am OK with not fixing this issue, however we will need to have a message in the sim when it is published that detects IE11 and shows a message.

Tagging for work to be done in https://github.com/phetsims/chipper/issues/954

**Comment by zepumph** [comment]
https://github.com/phetsims/chipper/issues/954 is implemented and no longer blocking. Not sure how that applies to this issue.

**Comment by zepumph** [comment]
From dev meeting today, @ariel-phet wants someone to build this sim, test that the IE message works on IE, and then this can unblock. I volunteered!

**Comment by zepumph** [comment]
I build density out of master, and ran it in IE with a link like http://localhost:8080/density/build/phet/density_en_phet.html. Here is the screenshot:

![image](https://user-images.githubusercontent.com/6856943/87102073-3814df00-c1fd-11ea-83a9-239cfb347f02.png)


It loaded successfully on Chrome. Over to @ariel-phet.

**Comment by ariel-phet** [comment]
Looks good, closing
