### ISSUE TITLE
Block 1D in Mystery Screen set 1 seems to have different collision than other blocks

### ISSUE THREAD

**Issue by loganbraywork** [phetsims/density#30]
**Test device**

Windows 10 Laptop

**Operating System**

Windows 10 v. 1903

**Browser**

Chrome Version 83.0.4103.97 

**Problem description**

For https://github.com/phetsims/QA/issues/507

Wasn't sure if this issue was addressed in https://github.com/phetsims/density/issues/19. If so feel free to close. 

Block 1D in the Mystery Screen, Set 1, seems to have different collision properties than any other encountered blocks in any screen or set. Block 1D seems to be able to clip into most blocks it is pressed against, as opposed to other blocks.

**Steps to reproduce**

1. Enter the Mystery Screen.
2. Manipulate 1D, attempting to compress blocks 1A and 1B for example

**Visuals**

![2020-06-15DensityD1Collsion](https://user-images.githubusercontent.com/54685448/84706707-b0e48c00-af1a-11ea-8d66-cf9e97927471.gif)

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Density‬
URL: https://phet-dev.colorado.edu/html/density/1.0.0-dev.11/phet/density_all_phet.html
Version: 1.0.0-dev.11 2020-06-03 18:06:51 UTC
Features missing: generatedcontent, csstransforms3d, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36
Language: en-US
Window: 1576x776
Pixel Ratio: 1.21875/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4095
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

**Comment by DianaTavares** [comment]
This is generated by the same issue that #19. I am going to close this issue for not to duplicate.
