### ISSUE TITLE
Sim seems to take a lot of power/memory leak

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/density#32]
For https://github.com/phetsims/QA/issues/507.
After opening the sim for about a minute, the fan on my computer started running very loudly. I hadn't started much yet, but the device was still seeming to struggle to keep up. Haven't seen this to this extent in other sims, so I think it is a density issue. I'll post a memory test here as well. @jonathanolson if there is another measure that would be helpful, let me know.

**Comment by KatieWoe** [comment]
After about two minutes of fuzzing the sim seems to crash, reload, and says that WebGL is not Available.
![crash](https://user-images.githubusercontent.com/41024075/84935195-997dde00-b095-11ea-8410-7c8fb0b63ff3.png)

**Comment by jonathanolson** [comment]
I've fixed a large number of things related to this. @KatieWoe would you be able to verify that master is doing acceptably? (I'm checking into what may be an incredibly slow memory leak, but I'll need to wait a number of hours of fuzzing before easily being able to isolate it).

**Comment by KatieWoe** [comment]
Memory test seems much better. Fan was running but not nearly as hard. I did notice that the fuzz test paused at times, which seemed a bit odd, but not necessarily a problem.
Memory test on master, 8/4/2020:
![looksbetter](https://user-images.githubusercontent.com/41024075/89351820-03673c80-d670-11ea-862d-73aa785bf122.png)

**Comment by arouinfar** [comment]
This issue is very stale and predates the 1.0 publication of this simulation. @KatieWoe reported improvement, and there haven't been any issues of user-reported performance issues since then. Closing.
