### ISSUE TITLE
Oddly bouncing block

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/density#33]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/507
When adjusting the density of a block, it may shoot up into the air, off the screen, and come down to bounce on the water in a way that looks very odd/buggy.
**Steps to reproduce**
1. Go to the first screen
2. Set the material to custom
3. Make the block heavy, then quickly make it light.

**Visuals**
![superbouncyblock](https://user-images.githubusercontent.com/41024075/84937084-77398f80-b098-11ea-9edf-e8fb41e19467.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Density‬
URL: https://phet-dev.colorado.edu/html/density/1.0.0-dev.11/phet/density_all_phet.html
Version: 1.0.0-dev.11 2020-06-03 18:06:51 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by DianaTavares** [comment]
I think that it is a normal buoyancy force pushing out of the water an object with a huge volume and low weight. The same happens when you try to force the block going down into the water:

![Density](https://user-images.githubusercontent.com/26031501/87094133-ffc4cf00-c203-11ea-8e2c-62d257d053f9.gif)

I don't think that it is a bug. @arouinfar, what do you think?

**Comment by arouinfar** [comment]
@DianaTavares I would agree that it's not a bug, but just an extreme density/buoyant force.
