### ISSUE TITLE
Long strings cause control panel crowding  in Intro screen 

### ISSUE THREAD

**Issue by loganbraywork** [phetsims/density#34]
**Test device**

Windows 10 Laptop

**Operating System**

Windows 10 v.1903

**Browser**

Chrome Version 83.0.4103.106 (Official Build) (64-bit)

**Problem description**

For https://github.com/phetsims/QA/issues/507

It seems that long strings cause significant crowding around the control panel in the Intro screen. The long string also shrinks the thumbs. The issue does not seem to appear in other screens.

**Visuals**

![2020-06-17LongStringtestDensity](https://user-images.githubusercontent.com/54685448/84951439-ac9ca800-b0ad-11ea-983a-1978b4f19cfb.PNG)

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: 12345678901234567890123456789012345678901234567890
URL: https://phet-dev.colorado.edu/html/density/1.0.0-dev.11/phet/density_all_phet.html?stringTest=long
Version: 1.0.0-dev.11 2020-06-03 18:06:51 UTC
Features missing: generatedcontent, csstransforms3d, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36
Language: en-US
Window: 1576x776
Pixel Ratio: 1.21875/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4095
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

**Comment by jonathanolson** [comment]
@ariel-phet what should the desired behavior here be? Currently NumberControl has the ArrowButton height hard-coded to match the height of the NumberDisplay.

**Comment by ariel-phet** [comment]
@jonathanolson - I think what is causing the issue here is that NumberDisplay is changing height, which just seems wrong to me. When I look at `?stringTest=Double` things start to get a bit funky.

![density](https://user-images.githubusercontent.com/4051174/86307495-21a2ce00-bbd4-11ea-9b55-aebe6b9e740a.PNG)

It seems to me that in these case the NumberDisplay should have some option where the strings inside it shrink but the NumberDisplay itself is a fixed size. Especially for a case like this, in reality the string for the units might get translated but it is unlikely to be long. And the layout gets very messed up if the NumberDisplays associated with the sliders are different sizes.

**Comment by arouinfar** [comment]
I've generally ignored the the appearance of the NumberDisplay when using a `stringTest` so long as the layout doesn't break for `long` and the text is readable for `double`. Realistically, the string in the NumberDisplay will not change. Worst case the abbreviated unit may pick up an additional character, and I'm not sure that will be enough of a change to result in smaller tweaker buttons.

Here's an example from Wave Interference. The NumberControl titles have definitely gotten smaller, but the the readout and tweaker button size is unchanged.
![image](https://user-images.githubusercontent.com/8419308/87630547-96a4f600-c6f2-11ea-9dbc-402da11e0f49.png)


For comparison purposes, this is what `stringTest=double` looks like in that sim:
<img src="https://user-images.githubusercontent.com/8419308/87630531-868d1680-c6f2-11ea-93a2-03944b313837.png" width=250>

**Comment by jonathanolson** [comment]
I believe the above commits should handle that correctly (and provides an option to do that for future code). Can you verify the appearance?

**Comment by arouinfar** [comment]
@jonathanolson  the layout is looking good on master.

| Default | `stringTest=double` | `stringTest=long` |
| --- | --- |--- |
| ![image](https://user-images.githubusercontent.com/8419308/93274083-b7cba680-f776-11ea-838c-579ea704ff23.png) | ![image](https://user-images.githubusercontent.com/8419308/93274119-cfa32a80-f776-11ea-88ca-4ec6645f71ac.png) | ![image](https://user-images.githubusercontent.com/8419308/93274074-b1d5c580-f776-11ea-9549-60c6567b7fd9.png) |
