### ISSUE TITLE
Larger block labels do not change color when in water as smaller block labels do

### ISSUE THREAD

**Issue by loganbraywork** [phetsims/density#35]
**Test device**

Windows 10 Laptop

**Operating System**

Windows 10 v. 1903

**Browser**

Firefox 77.0.1

**Problem description**

For https://github.com/phetsims/QA/issues/507

Larger block labels do not seem to gain the same water shading effect that smaller blocks do, even when the label is at the same relative height to smaller blocks. There also appears to be some inconsistency in shading between smaller blocks, with some blocks taking on the water color at a greater height than other blocks.

**Steps to reproduce**

1. Enter the Mystery Screen
2. Place Block 1D and block 1A into the water
3. Lift block 1A so that the label is at the same height as block 1D

**Visuals**

In the visual, it is also easy to observe the variance in block shading based on height

![2020-06-17DensityWaterColor](https://user-images.githubusercontent.com/54685448/84958587-ed4eee00-b0ba-11ea-9283-1b4527fa9a75.gif)

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Density‬
URL: https://phet-dev.colorado.edu/html/density/1.0.0-dev.11/phet/density_all_phet.html
Version: 1.0.0-dev.11 2020-06-03 18:06:51 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0
Language: en-US
Window: 1568x768
Pixel Ratio: 1.2244897959183674/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 30 uniform: 4095
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

**Comment by muedli** [comment]
@loganbraywork, it looks like there are some trailing artifacts from the blocks. For example, when you move block 2C up and back down, there's a horizontal green line left behind. Does this happen on your computer or is it a result of recording the gif?

**Comment by loganbraywork** [comment]
This is a result of the recording itself, does not naturally appear on my computer

**Comment by DianaTavares** [comment]
In the design meeting today we discuss putting the labels of all the blocks in front of the water. This apply for the blocks in the intro and mystery screen. 

![image](https://user-images.githubusercontent.com/26031501/87093317-9f815d80-c202-11ea-9cde-2192f5ac3581.png)

**Comment by jonathanolson** [comment]
I believe all of the cube labels should appear with no water effect now, can you verify in master?

**Comment by DianaTavares** [comment]
Yes, this is fix!!
