### ISSUE TITLE
Less bounce on blocks in water

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/density#37]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/507. More of a sim suggestion than a bug.
When a block is dropped on to the water, it bobs up and down. It can do this for a fair amount of time. I am wondering if it would be a good idea for it to settle faster, or if that would look wrong.

**Visuals**
![dampenbounce](https://user-images.githubusercontent.com/41024075/86402614-5c0a7a80-bc69-11ea-91aa-dfac95c76da1.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Density‬
URL: https://phet-dev.colorado.edu/html/density/1.0.0-dev.11/phet/density_all_phet.html
Version: 1.0.0-dev.11 2020-06-03 18:06:51 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by DianaTavares** [comment]
Past versions of the sim used to bounce a lot more. when @jonathanolson shows these bobs up and down in a previous design meeting, @arouinfar  and I look it as an improvement. I think that the movement is acceptable. What do you think @arouinfar?  @jonathanolson, is easy to reduce the bounce?

**Comment by arouinfar** [comment]
@DianaTavares I do think the bounce is better than it used to be. It can take some time for the volume to equilibrate if a block is dropped from a large height, but it happens fairly quickly if released closer to the water. You might be able to increase the damping a bit more, but I don't think it's necessary.

**Comment by DianaTavares** [comment]
@jonathanolson is going to play with the viscosity values to get less bounce. The effect of this is stronger when the block in the bottom has a very small density

**Comment by jonathanolson** [comment]
I've adjusted the minimum viscosity effect (primarily for low-mass objects). Can you take it for a test drive to see how it works?

**Comment by DianaTavares** [comment]
I think it is good! that buoyancy I think is normal and acceptable for the sim.
