### ISSUE TITLE
Odd shading behavior on wood, aluminum, and ice

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/density#38]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/507
When moving the wood and aluminum blocks up and down, the shading on the sides behaves oddly. Going in and out of the pool changes the top of the block, and going above the horizon changes the side. The ice block also seems to have some odd shading, but the transparency makes it appear differently.

**Visuals**
![oddshading](https://user-images.githubusercontent.com/41024075/86407429-42216580-bc72-11ea-9cf9-844051419702.gif)
![oddshading2](https://user-images.githubusercontent.com/41024075/86407441-48afdd00-bc72-11ea-95ee-b45a22e3d607.png)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Density‬
URL: https://phet-dev.colorado.edu/html/density/1.0.0-dev.11/phet/density_all_phet.html
Version: 1.0.0-dev.11 2020-06-03 18:06:51 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by jonathanolson** [comment]
The water-interaction should be changed now, although some reflectivity of the horizon is still visible on the side. @DianaTavares is there anything that should be changed for the current behavior?

**Comment by DianaTavares** [comment]
I think that the behavior is ok! I see the reflectivity on the horizon when the block is going up to the top of the sim, but I am just thinking in @ariel-phet  comment "just normal interaction with the sim". Then I think that the improvements are enough.
