### ISSUE TITLE
modify the values of the mystery blocks to have integer numbers in one of the variables 

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/density#40]
In the last design meeting, @kathy-phet suggested modifying the values of the mystery blocks for having integer numbers in one of their variables. Only SET 1 has this issue (the other two sets already has one of the variables with an integer value). 

The mystery sets have two blocks with the same mass, two with the same density and two with the same volume (this configuration makes that only one block need to have both values with decimals). 

Another of the issues with the SET1 was the huge differences in the mass values (#19). Then, if the values of the blocks variables are going to change, I decide to make smaller the blocks with high density and bigger the blocks with smaller density to reduce these mass differences (already approved by @ariel-phet ).  The new proposal fo the values of the blocks are (bock A is the only block that doesn't change):

-- | A | B | C | D | E
-- | -- | -- | -- | -- | --
Mass | 3.51 | 2.72 | 3.68 | 19.32 | 3.51
Volume | 1 | 4 | 4 | 1 | 5.16
Density | 3.51 | 0.68 | 0.92 | 19.32 | 0.68

**Comment by jonathanolson** [comment]
Implemented, however with D being smaller in volume than C, the order seems a bit off:

<img width="674" alt="Screen Shot 2020-07-23 at 9 24 02 AM" src="https://user-images.githubusercontent.com/480878/88305111-592e0300-ccc6-11ea-89e3-5915167bbf07.png">

Is it ok to have the D block above the C block, or should they be reversed?

**Comment by DianaTavares** [comment]
Nide, thank you, Jonathan! in that case just to change the labels. Yellow block with the 1C label, and red block 1D

**Comment by jonathanolson** [comment]
I pushed the label fix, AND hit the pull button for density-buoyancy-common on phettest. Can you see if that solved (both) problems?

**Comment by DianaTavares** [comment]
It is solved, thanks!
