### ISSUE TITLE
create a new dev version 

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/density#41]
For Density: Create a new dev version that includes the changes suggested in issue #40, min mass for the custom block of 0.5 kg in the Intro screen, and the query parameters of this link:

http://phettest.colorado.edu/density/density_en.html?ea&brand=phet&p2PointerMassForce=0&p2PointerBaseForce=2500&p2FrictionIterations=500

for Buoyancy:
http://phettest.colorado.edu/buoyancy/buoyancy_en.html?ea&brand=phet&p2PointerMassForce=0&p2PointerBaseForce=2500&p2FrictionIterations=500

**Comment by jonathanolson** [comment]
Dev version available at https://phet-dev.colorado.edu/html/density/1.0.0-dev.12/phet/density_en_phet.html
