### ISSUE TITLE
The labels of small blocks overlap with blocks next to them

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/density#42]
**Test device** 
MacBook

**Operating System**
macOS Mojave version 10.14.6

**Browser**
Chrome

**Problem description**
When a block is placed to the left of a smaller block, the label of the smaller block overlaps a little bit with the bigger block. 

**Steps to reproduce**
1.- place a  small block to the right in the ground 
2.- move a bigger block close to the small block 

**Visuals**
![image](https://user-images.githubusercontent.com/26031501/87588722-bd8b0a00-c6a9-11ea-8e4b-9bd15ec65a89.png)

![Untitled](https://user-images.githubusercontent.com/26031501/87589115-60438880-c6aa-11ea-860e-6f7005ae638c.gif)

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Density‬
URL: http://phet.colorado.edu/sims/html/density/latest/density_en.html
Version: 1.0.0-dev.9 2020-05-08 14:46:54 UTC
Features missing: generatedcontent, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36
Language: es-419
Window: 1715x977
Pixel Ratio: 0.8999999761581421/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

**Comment by jonathanolson** [comment]
Is this still a problem with the newer parameters? I can't seem to reproduce it.

**Comment by DianaTavares** [comment]
I still see them:
![image](https://user-images.githubusercontent.com/26031501/88314933-4245db80-ccdb-11ea-9f04-fb3a0f8a51cc.png)

@KatieWoe, can you review if this happen in other computers? it is not the first time that I have and specific computer issue.

**Comment by KatieWoe** [comment]
I could also reproduce with Win 10 Chrome on master.

**Comment by jonathanolson** [comment]
Thanks! Looking into it.

**Comment by jonathanolson** [comment]
The core of this issue is the desire to (a) have the block labels appear as if they're in front of the water, (b) have the blocks appear behind water and (c) have a block label from one block appear behind another block. This is essentially a rock-paper-scissors configuration that's somewhat tricky to resolve in general, I'm close to having a resolution.

**Comment by jonathanolson** [comment]
I believe the above commits should finally handle this, can you verify?

**Comment by DianaTavares** [comment]
It is working amazingly! thanks!!
