### ISSUE TITLE
fast test for the new density dev version in low performance platforms 

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/density#43]
We have a new dev version of the Density sim:
https://phet-dev.colorado.edu/html/density/1.0.0-dev.12/phet/density_en_phet.html

We are worried that it can be slow for some platforms. Please test it and review that:

- The sim doesn't get slow 
- The sim doesn't take a lot of power/memory (issue #32)
- When you put one more massive block over another lighter, they don't overlap (issue #19), or go through the ground (issue #39)
- Anything goes throw the ground (issue #26)
- And the lag when dragging/moving objects don't increase a lot (issue #36) when the blocks move to a "normal" velocity (I already see that when the blocks move super-fast, this problem is distracting, but @ariel-phet surgest to test it in typical usage of the sim).

**Comment by KatieWoe** [comment]
- [ ] Win 10 Chrome
- [ ] Win 10 Firefox
- [ ] Win 10 Edge
- [ ] Mac 10.12 Safari
- [ ] Mac 10.15 Safari
- [ ] ChromeOS
- [ ] iPadOS 13 Safari

**Comment by KatieWoe** [comment]
Is the above an acceptable range of testing @DianaTavares

**Comment by KatieWoe** [comment]
Memory leak seems a bit better, but still there. The page crashed after 6 minutes, but it went dark so I only captured these results:
![stillbig](https://user-images.githubusercontent.com/41024075/87732138-5e9cc200-c789-11ea-934d-6af921c26b3b.png)

**Comment by KatieWoe** [comment]
It was getting up to 400MB

**Comment by DianaTavares** [comment]
> Is the above an acceptable range of testing @DianaTavares

Yes, thanks!!

**Comment by KatieWoe** [comment]
I redid the memory test to get the later numbers.
Start: 25.6 MB
1 min: 117 MB
2 min: 183 MB
3 min: 239 MB
4 min: 310 MB
5 min: 368 MB
6 min: 429 MB and dev tools crashed right after

**Comment by ariel-phet** [comment]
This issue is stale, once physics engine issues are resolved we will look into performance again as we move towards publication. Closing.
