### ISSUE TITLE
A graphical error occured

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/density#44]
For https://github.com/phetsims/QA/issues/507.
I was opening a new tab to check the sim in master, and as I did both the dev version and the master version seemed to have a graphical error. In the dev version, objects disappeared and an error popped up. Bellow is the error and the console read-out.
![grapherrorconsole](https://user-images.githubusercontent.com/41024075/90831410-dddd6280-e300-11ea-8a92-595b17f03d83.png)
![graphicserror](https://user-images.githubusercontent.com/41024075/90831415-dfa72600-e300-11ea-9a53-40bed61852e4.png)
The sim had not been open for particularly long when this occurred. Seen on Win 10 Chrome

**Comment by KatieWoe** [comment]
The page crashes, goes black, and reloads without graphics after about 3 minutes of fuzz testing.
![thrreminutefuzz](https://user-images.githubusercontent.com/41024075/90831761-ade28f00-e301-11ea-8b2f-28ecb07d9796.png)

**Comment by phet-steele** [comment]
@KatieWoe requested that I reproduce, and here are my results:

Took me 5 sim tabs before I lost WebGL context in the oldest sim, which is more or less expected to me. (Win 10 Chrome)

**Comment by KatieWoe** [comment]
Also noting that when I opened multiple tabs of the dev version in the regular browser (3) I wasn't getting this like I was with one dev in regular and one master copy in incognito.

**Comment by loganbraywork** [comment]
I also had a graphical error once while testing an issue while master and the dev version were both open. I haven't been able to reproduce it again, but only the two sims were open. I remember it occurred while I had opened ScreenToGif to record the screen, so I had assumed it was resultant of that.

**Comment by jonathanolson** [comment]
I've moved the icons to by default be loaded as images (instead of generated). This means we create 5 fewer WebGL contexts, and I believe it may help with this.

@KatieWoe or @phet-steele, could you test https://bayes.colorado.edu/dev/phettest/density/build/phet/density_en_phet.html (I rebuilt after pulling) to see if it behaves a bit better? There is a moderate chance it will behave the same.

Additionally, platform/browser information here helps a lot (even if it's laptop vs desktop, due to GPU differences).

**Comment by KatieWoe** [comment]
About 5 tabs open before graphical issue occurred on Win 10 Chrome incognito. I also did a fuzz test with iPadOS 14 and the crash and reload was almost immediate.

**Comment by jonathanolson** [comment]
Testing locally on 2017 Macbook Pro, I have ~5 instances of Density/Buoyancy in my main window, and another 10 running nicely in an incognito window (Chrome 89).

I'll test on my Windows setup and iPhone (with fuzz)

**Comment by jonathanolson** [comment]
iPhone testing seemed fine while fuzzing, did not crash (watched it for at least a few minutes), 10min of fuzzing seemed fine after.

Windows incognito with 5 tabs, got this:

![image](https://user-images.githubusercontent.com/480878/114757425-14953c80-9d19-11eb-8ff7-35fe18b06ddf.png)

and the graphics error.

I'll look into seeing whether we can re-load the view based on this.

**Comment by jonathanolson** [comment]
@kathy-phet and @arouinfar, it seems like this MAY be resolvable, but would take a significant amount (week?) of work. Thoughts on whether this is acceptable, or should I proceed with attempting to resolve this?

**Comment by arouinfar** [comment]
From what I understand, this only happens if someone opens up 5+ tabs of the **sim** (not just browser tabs). Is that correct? If so, it doesn't seem like a reasonable use case that's worth spending a week of your time on @jonathanolson.

**Comment by jonathanolson** [comment]
> Is that correct?

That's my current understanding, however other WebGL-using pages could trigger this too. We currently create 3 contexts (although this could potentially be taken down to 1 with a moderate amount of work), so anything else that creates ~12 contexts would likely also do this.

**Comment by zepumph** [comment]
For this issue @zepumph and @AgustinVallejo will:
1. Determine how many contexts Buoyancy is currently making.
2. Ensure that all icon generation involving three js is hidden behind the image generation.
3. Make sure that we are "cleaning up" contexts if we need to create/destroy them (I doubt we do). 
4. I opened 10 tabs of buoyancy in one window, and 2 more in another window, and didn't reproduce this problem. We will try next time with more contexts using `generateIconImages`. (especially once we get https://github.com/phetsims/buoyancy/issues/48 done).

**Comment by samreid** [comment]
I confirmed the 2 bonus contexts are both in scenery checking for webgl or stencil support.

**Comment by samreid** [comment]
I visited the parts in https://github.com/phetsims/density/issues/44#issuecomment-1939216979 and experimented/commented on them. It seems this issue is OK to close and we can reopen any time if needed.
