### ISSUE TITLE
Blocks switch spots

### ISSUE THREAD

**Issue by loganbraywork** [phetsims/density#45]
<b>Test Device</b>

Windows 10 Laptop

<b>Operating System</b>

1903

<b>Browser</b>

Version 84.0.4147.135 

<b>Problem Description</b>

For https://github.com/phetsims/QA/issues/507. Appears in the current master version of the sim as well.

When on the Compare screen, and blocks are set to the same density, it is possible to swap the positions of blocks by pressing them into each other.

<b>Steps to Reproduce</b>

1. Enter the compare screen
2. Select the Same Density radio button
3. Order the blocks by size, smallest to largest
4. Swap the positions of the smallest and second smallest blocks
5. Using the largest block, repeatedly move the largest block into the side of the second largest, so that all blocks collide.

<b>Visuals</b>

![2020-08-20Density](https://user-images.githubusercontent.com/54685448/90832073-424cf180-e302-11ea-85fb-d4fbaaa81d52.gif)

<details>
<b><summary> Troubleshooting Information </summary></b> 
Name: Density
URL: http://phettest.colorado.edu/density/density_en.html?ea&brand=phet
Version: 1.0.0-dev.14 (unbuilt)
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36
Language: en-US
Window: 1433x706
Pixel Ratio: 1.3406250476837158/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4095
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by jonathanolson** [comment]
@ariel-phet, I'm curious what the severity of this is? It looks like due to the slop in the physics engine and overlap related to https://github.com/phetsims/density/issues/19, this can happen. If that gets handled, this should be resolved.

**Comment by ariel-phet** [comment]
@jonathanolson -- this issue is not severe at all. What is being done in the example is not a pedagogically valuable use case at all. If #19 fixes this case, great, if not, this issue can be marked as `wontfix` in my opinion. Marking deferred for now, until #19 gets a resolution.

**Comment by zepumph** [comment]
@AgustinVallejo and I want to connect this issue to https://github.com/phetsims/buoyancy/issues/89, which is also about slop in the physics engine's mass boundaries. Let's work on them together. It's possible that tradeoffs mean that we decide not to make any changes.

**Comment by zepumph** [comment]
As discussed in Design meeting today, we are going to defer this issue because the graphics model is sensitive and we should focus on publishing instead of making all interactions perfect (since it doesn't break anything). Deferring.

**Comment by samreid** [comment]
Based on the remarks above, can this be closed as "will not fix"?

**Comment by samreid** [comment]
@DianaTavares @zepumph and I agreed to close the issue.
