### ISSUE TITLE
Sliders do not behave consistently

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/density#46]
**Device**
iPad 6th Gen
**OS**
iPadOS 13.6.1
**Browser**
Safari
**Problem Description**
For https://github.com/phetsims/QA/issues/507.
On the first screen, you can control the mass and the volume. Since, for most of the material options, the density is set, changing on variable simultaneously changes the other. In some instances, what can be reached by manipulating the thumb on a slider, what can be reached with the buttons, and what can be reached by manipulating the other variable are all different, even if it doesn't seem like that should be the case by looking at the sliders. This seems to occur with the Styrofoam and ice options.

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/41024075/90911568-6a863000-e396-11ea-9917-6ee2a242e6c7.gif)
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/41024075/90911583-6eb24d80-e396-11ea-9aaf-f99c2b06ff12.gif)

**Comment by KatieWoe** [comment]
With the Styrofoam example, if it gets to its minimum mass by changing volume, the spinner button for decreasing the mass still looks enabled. Pressing it disables it. Visual bellow.
![boldedarrow](https://user-images.githubusercontent.com/41024075/91222632-b27dbd80-e6dc-11ea-91d3-8d9dba8df05d.gif)

**Comment by phet-steele** [comment]
https://github.com/phetsims/density/issues/46#issuecomment-680244586 was reported as #49

**Comment by jonathanolson** [comment]
I believe this is fixed, except for the ice case. It seems like our choice to limit the mass slider/buttons to X.X0 won't let it get to the minimum styrofoam value (0.15). Thoughts on how to proceed?

**Comment by DianaTavares** [comment]
Now I see that when one of the sliders goes to the stream values, both buttons (volume and mass) get inactive with a gray color. But when I change from one material to another one in the minimum value, the mass button is active, but the value is minimum, then it is not another value smaller.

![Density.gif](https://images.zenhubusercontent.com/5fc925cacd9489e51df9c54d/d8816729-5606-44aa-a105-b5c8284b6b3b) 

desired behavior: when the volume value is minimal, and the button is inactive, the mass value should be minimal as well and the bottom inactive. 

The behavior with the max values is correct:

![Density 2.gif](https://images.zenhubusercontent.com/5fc925cacd9489e51df9c54d/58171df0-bea3-4710-9538-965ac960d413)

**Comment by DianaTavares** [comment]
The mass slider moves in steps of 0.10 kg. Then, for the materials that have a min value that has a 0.0X decimal (like the styrofoam that the min mass is 0.15, and ice that is 0.92), the user can not access that values with the slider and need to use the buttons or the volume slider. 

I don't see this as a bug, and the sim can stay like it is.

**Comment by Nancy-Salpepi** [comment]
**Test device**
MacBook Air (and Chromebook)

**Operating System**
12.0.1

**Browser**
chrome and safari

**Problem description**
For https://github.com/phetsims/qa/issues/751

In the intro screen, it looks odd that the User can't reach the minimum mass for styrofoam using the slider. Instead, the left arrow or the volume slider must be used. This doesn't happen with any other material.

**Steps to reproduce**
1. On the Intro Screen, select 'styrofoam' as the material
2. Drag the Mass slider all the way to the left--it stops at 0.20kg. 
3. Use the left arrow or the volume slider to decrease the mass to 0.15kg

**Visuals**
![styrofoammass](https://user-images.githubusercontent.com/87318828/145909333-2ad35ac3-a0a8-45c7-b57f-84af450ad2b4.gif)

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Density‬
URL: https://phet-dev.colorado.edu/html/density/1.0.0-dev.20/phet/density_all_phet.html
Version: 1.0.0-dev.20 2021-12-10 16:54:23 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36
Language: en-US
Window: 1440x690
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by kathy-phet** [comment]
@jonathanolson - Can you make this slider for Styrofoam mass behave like the "Ice" slider? Where it will snap to 0.1 values, but then also still reach the minimum and maximum values allowed? Ice can be directly dragged down to reach 0.92 (so a non-snappy value).

**Comment by Nancy-Salpepi** [comment]
@jonathanolson --Should the maximum mass for ice be changed to 9.20 instead of 9.19?

**Comment by jonathanolson** [comment]
> Can you make this slider for Styrofoam mass behave like the "Ice" slider?

Implemented above, there was some weirdness in the snapping (it was snapping BEFORE the range constraints, and styrofoam's min was too low).

**Comment by jonathanolson** [comment]
> Should the maximum mass for ice be changed to 9.20 instead of 9.19?

This would mean changing the density of ice (since it's based on that).

**Comment by jonathanolson** [comment]
@arouinfar anything else to do here?

**Comment by arouinfar** [comment]
@jonathanolson looks good in master. Back to you to either close or verify in the RC.
