### ISSUE TITLE
Possible to both grab block and change it with slider with one finger

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/density#47]
Device
iPad 6th Gen
OS
iPadOS 13.6.1
Browser
Safari
Problem Description
For https://github.com/phetsims/QA/issues/507
When dragging a block in the first screen with touch, if your finger passes over the thumb of a slider, it will snag and pick it up. Both will be changed with the one finger.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/41024075/90924795-56016200-e3ad-11ea-9936-465a7d465e88.gif)

**Comment by jonathanolson** [comment]
I believe this has been fixed by the above commit in master, can you verify?

**Comment by KatieWoe** [comment]
Looks good on master

**Comment by jonathanolson** [comment]
Thanks!
