### ISSUE TITLE
When trying to submerge block, it gets caught on the edges of the pool

### ISSUE THREAD

**Issue by liam-mulhall** [phetsims/density#48]
<b>Test Device</b>

MacBook Air

<b>Operating System</b>

macOS 10.15.5

<b>Browser</b>

Firefox 79.0

<b>Problem Description</b>

For https://github.com/phetsims/QA/issues/507. When trying to submerge a block when flush against one of the edges of the pool, it'll get "caught" on the edge of the pool. See gif below. You can't fully submerge the block if it's flush against one of the edges of the pool.

<b>Steps to Reproduce</b>

1. Intro screen.
2. Select the "Custom" block.
3. Minimum mass.
4. Maximum volume.
5. Try to submerge block while it's flush against one of the edges of the pool.

<b>Visuals</b>

![issue](https://user-images.githubusercontent.com/60749003/90931159-42f48f00-e3b9-11ea-9bbf-6a2d7a55d624.gif)

<details>
<summary><b>Troubleshooting Information</b></summary>

!!!!! DO NOT EDIT !!!!!
Name: ‪Density‬
URL: https://phet-dev.colorado.edu/html/density/1.0.0-dev.11/phet/density_all_phet.html
Version: 1.0.0-dev.11 2020-06-03 18:06:51 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:79.0) Gecko/20100101 Firefox/79.0
Language: en-US
Window: 1280x748
Pixel Ratio: 1/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 8192 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by DianaTavares** [comment]
When I try to submerge the block flush against the edges of the pool by just pulling down the block, I can not reproduce this behavior with the sim versions: https://phet-dev.colorado.edu/html/density/1.0.0-dev.15/phet/density_en_phet.html, 

if I generate a "force" by dragging diagonally the block in the direction of the wall I get the behavior reported in issue #53

Closing this issue.
