### ISSUE TITLE
Republish Density prototype

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/density#52]
It would be nice to republish Density with the new prototype build process so that the prototype link is added to the sim page!

**Comment by jonathanolson** [comment]
https://phet-dev.colorado.edu/html/density/1.0.0-dev.15/phet/density_en_phet.html is a candidate for this, @DianaTavares. Let me know how it looks?

**Comment by DianaTavares** [comment]
this version has better behavior than the one in the prototype section on the website (I see that #19 still happening.  I am going to report that in the issue). Then I suggest changing the sim in the prototype section for this new version. 

@jonathanolson  Let me know when the new version is on the website to close this issue. Thanks!!

**Comment by DianaTavares** [comment]
@arouinfar suggested by slack that is better to wait for a new prototype version when the simulation has fewer bugs.

**Comment by DianaTavares** [comment]
this is not needed anymore. The sim is almost ready to publish!
