### ISSUE TITLE
Blocks can get partially stuck inside the side and lower walls while submerged

### ISSUE THREAD

**Issue by brooklynlash** [phetsims/density#53]
**Test device**
Lenovo ThinkPad

**Operating System**
Windows 10

**Browser**
Chrome, Edge, Firefox

**Problem description**
When dragging a block quickly to the side, it gets stuck in the walls as if it is about to bounce around and goes back and forth. 
This works for all three sections and was also replicated on master.
**Steps to reproduce**
1. Open one of the sections of the sim (I used Intro for the gif)
2. Grab the block
3. Drag it quickly to any edge under water
4. Observe

**Visuals**
This gif is from the Edge browser, which showed it the best, but note that it is going much faster when actually replicating the issue. 

![densityedge](https://user-images.githubusercontent.com/72031637/97214600-f185c900-1788-11eb-9a7b-77ea3357a9d6.gif)

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Density‬
URL: https://phet-dev.colorado.edu/html/density/1.0.0-dev.11/phet/density_all_phet.html
Version: 1.0.0-dev.11 2020-06-03 18:06:51 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36
Language: en-US
Window: 1707x818
Pixel Ratio: 2.25/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4095
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

**Comment by brooklynlash** [comment]
Can also get a block stuck in another for a second before returning to normal

**Comment by DianaTavares** [comment]
this behavior still present in the versions: https://phet-dev.colorado.edu/html/density/1.0.0-dev.15/phet/density_en_phet.html


https://user-images.githubusercontent.com/26031501/112073117-03517980-8b39-11eb-896c-eb9af6ba797a.mov


It is the only strange behavior that remains from issue #19. Then I am going to leave this issue open, and close #19 to have a more clear discussion.

**Comment by jonathanolson** [comment]
@KatieWoe, @DianaTavares or @arouinfar, can we test with the query parameter p2GroundRelaxation=2.5 to see if that is sufficient? (The default value is 1)

The note for this parameter is "reduction results in less ground penetration when a mass is sitting on the ground", so we'd want to ensure that increasing it wouldn't result in too much ground penetration.

**Comment by KatieWoe** [comment]
On master that parameter does seem to stop the issue.
Master without parameter:
![noparameter](https://user-images.githubusercontent.com/41024075/114752644-c6ca0580-9d13-11eb-8ee6-df233118aa59.gif)
Master with parameter:
![withparameter](https://user-images.githubusercontent.com/41024075/114752689-d21d3100-9d13-11eb-93fb-b63aa08197cd.gif)

**Comment by jonathanolson** [comment]
Ok! Committed that as a default so that could make testing easier.

**Comment by DianaTavares** [comment]
I also review it with the query parameter and I have the same results that @KatieWoe. Nice!!

**Comment by arouinfar** [comment]
Looks great @jonathanolson!

**Comment by jonathanolson** [comment]
Perfect, closing!
