### ISSUE TITLE
HTML5 table values don't match Java

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/density#55]
I've had 2 users write in to phethelp about this and one of the emails was forwarded to @DianaTavares but I thought it should be captured in an issue.

> I'm converting my lab to use your new Density lab and came across a possible mistake on your sim.  Below is a screen-shot showing the new sim on the left and the old sim on the right.  The values on the density table changed.  The values in the new table no longer match the density of the blocks in Set 1 like they used to. For example, the blue block has a density of 0.64 kg/L.  In the old sim the table indicated that as an Apple but the new table doesn't have anything with a density value of 0.64 (the closest answer would be Gasoline at 0.68).  The green block has a density of 0.7 again not listed in the new table but again closest to Gasoline.  The values in the old table  match the densities of the blocks exactly which is more straightforward for students.

> There is a discrepancy between the Density Flash and HTML5 modules in the CUSTOM part.  Under CUSTOM  apple and gasoline and others are different in the new module (or wrong in the old)   Please correct.  

Java:
![image](https://user-images.githubusercontent.com/5090275/101556304-cb526c00-3977-11eb-9e72-171d867c1179.png)

HTML5:
![image](https://user-images.githubusercontent.com/5090275/101556322-cee5f300-3977-11eb-814d-edf54c8629b1.png)

**Comment by DianaTavares** [comment]
the mistakes with the values of the blocks were already modified in the master sim, but the prototype has not been updated. #51 is about that. I will close this issue, and I will remind @jonathanolson about update the prototype version.
thanks!!
