### ISSUE TITLE
Reset button in the Mystery screen break the simulation 

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/density#57]
I am using this link to the Density simulation: https://bayes.colorado.edu/dev/phettest/density/density_en.html?ea&brand=phet

When I go to the Mystery screen, Random option, and click the Reset button to have a new ser of mystery blocks, the blocks disappears and all the simulation stip working:

![image](https://user-images.githubusercontent.com/26031501/111676743-1afccb00-87e4-11eb-972d-d180e895857d.png)

Also, I try to get the information of "Report a problem" in the menu of the simulation:
![image](https://user-images.githubusercontent.com/26031501/111677225-a0807b00-87e4-11eb-9fb8-70836db79617.png)

and I get this error:
![image](https://user-images.githubusercontent.com/26031501/111677266-aaa27980-87e4-11eb-862e-2802d6eaa634.png)

The same happens when I click in the menu "PhET website"

**Comment by jonathanolson** [comment]
I believe the above commit should fix this. @arouinfar can you verify on master?

**Comment by arouinfar** [comment]
I'm unable to reproduce @jonathanolson, but I'll leave it to @DianaTavares to verify.

**Comment by DianaTavares** [comment]
the sim is working perfectly on my computer! closing the issue.
