### ISSUE TITLE
Icon perspective changes

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/density#58]
As discussed during design meeting, I'll have a commit coming soon, and will pass off once ready.

**Comment by jonathanolson** [comment]
Icons ready for viewing, let me know how they look. (Mystery screen icon and single/double mass switch icons). I vertically and horizontally aligned each mass icon.

**Comment by arouinfar** [comment]
Looks great @jonathanolson.

<img src="https://user-images.githubusercontent.com/8419308/111815255-134f2c00-88a1-11eb-8e99-e193c287e1e0.png" width=250>  
<img src="https://user-images.githubusercontent.com/8419308/111815280-1b0ed080-88a1-11eb-9201-922426023fb1.png" width=250>

**Comment by DianaTavares** [comment]
I love them! they look great. Closing this issue.
