### ISSUE TITLE
Mystery screen design

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/density#6]
The Mistery screen mockup is the next one:
![image](https://user-images.githubusercontent.com/26031501/74486940-e0f42380-4e83-11ea-8ab0-6276242fb6db.png)

The user can change click in the different radio buttons to have another set o blocks with mistery mass, volume, and density.  The values of the mystery objects are:

Set 1 (the same that flash version of the sim):

Colors | yellow | blue | green | red | Purple
-- |-- | -- | -- | -- | --
Mass | 65.30 Kg | 0.64 kg | 4.08 kg | 3.10 kg | 3.53 kg
Volume | 3.38 L | 1 L | 5.83 L | 3.38 L | 1 L
Density | 19.32 kg/L | 0.64 kg/L | 0.70 kg/L | 0.92 kg/L | 3.53 kg/L

Set 2 (where all the blocks sink):

Colors | Pink | Orange | Light purple | Light green | Brown
-- |-- | -- | -- | -- | --
Mass | 18 Kg | 18 kg | 44.45 kg | 2.7 kg | 10.8 kg
Volume | 4 L | 1.59 L | 5 L | 1 L | 4 L
Density | 4.5 kg/L | 11.34 kg/L | 8.89 kg/L | 2.7 kg/L | 2.7kg/L

Set 3

Colors | White | Gray | Mustards | Peach | Maroon
-- | -- | -- | -- | -- | --
Mass | 6 Kg | 6 kg | 2 kg | 23.4 kg | 2.85 kg
Volume | 6.31 L | 2 L | 5 L | 3 L | 3 L
Density | 0.95 kg/L | 1kg/L | 0.4 kg/L | 7.8 kg/L | 0.95 kg/L

For the random option, the sim selects 5 of the densities in the "Density of Varios Materials" (the density values can be the same for more of one block), randomly select a value for the volume between 1 to 10 (an integer) and calculate the mass according with the density of the material selected. For the color, can the sim also select a random color for the block? 

When the Random radio button is selected, a refresh button is going to appear. Clicking in this button is going to change to another random set of blocks. 

![image](https://user-images.githubusercontent.com/26031501/74487859-37faf800-4e86-11ea-8f1b-6ff8b4fe625a.png)

**Comment by jonathanolson** [comment]
Implemented the initial version of this, available at https://phet-dev.colorado.edu/html/density/1.0.0-dev.4/phet/density_en_phet.html.

Can I get feedback on how this looks/works?

**Comment by DianaTavares** [comment]
I think is very good! I don0t know if it is important, but looks a little strange when a very small block is under big blocks in the random option:

![image](https://user-images.githubusercontent.com/26031501/76262855-18f04b80-6223-11ea-94b5-105550183871.png)

Also, the scale must not be moved.

**Comment by jonathanolson** [comment]
Implemented both of those (should be up on phettest), let me know if you want another dev version.

**Comment by arouinfar** [comment]
@jonathanolson I like the new stacking order. 

I've noticed that roughly ~1/3 of the time, the stack of 3 blocks will have volumes large enough that the top block extends beyond the dev bounds. The sim is still usable in this state, but it does look a bit sloppy. @jonathanolson would there be a way to somehow limit the total volume to avoid this situation?

<img src="https://user-images.githubusercontent.com/8419308/76340588-70dd8f80-62c1-11ea-8d8e-1fced0569d79.png" width=250>

**Comment by jonathanolson** [comment]
I added a change that will put the largest blocks on the left, and ensure that there are enough smaller blocks where the stack of 3 on the right won't go past the top. Let me know how that looks?

**Comment by arouinfar** [comment]
@jonathanolson the new stacking strategy is looking good in master. 

> Also, the scale must not be moved.

It looks like the scale is non-pickable, which prevents the user from directly moving the scale. However, it is quite easy to move the scale by bumping into it with one of the blocks. I've accidentally knocked it off-screen a few times.

**Comment by jonathanolson** [comment]
> It looks like the scale is non-pickable, which prevents the user from directly moving the scale. However, it is quite easy to move the scale by bumping into it with one of the blocks. I've accidentally knocked it off-screen a few times.

Whoops! Assigning to fix that.

**Comment by jonathanolson** [comment]
Additional recommendations during design meeting:

Add a title on the Mystery screen for the "blocks" panel: "Blocks"
"Blocks Set 1" => "Set 1"

**Comment by jonathanolson** [comment]
Implemented in master, do the changes look good?

**Comment by DianaTavares** [comment]
Look nice, but I don see the labels:

 Mystery blocks with labels (top left?) with "1A", etc., or for random "A", "B" (left-to-right top-down)

**Comment by DianaTavares** [comment]
And I like more the panels with white color. What do you think @arouinfar ?

**Comment by arouinfar** [comment]
>Look nice, but I don see the labels

I'm seeing them in master @DianaTavares 
![Density screenshot](https://user-images.githubusercontent.com/8419308/77017094-15ee0d00-693f-11ea-8d76-1215c83c60ca.png)

> And I like more the panels with white color. What do you think @arouinfar ?

I think the controls blend in a bit too much on the white background. I prefer gray over white, but I think we could lighten the gray a bit to `rgb(240, 240, 240)` (right).
![image](https://user-images.githubusercontent.com/8419308/77017334-dd9afe80-693f-11ea-90c2-69f5b9cfc882.png)

I also think the Density scale on Intro and the Density table on Mystery should both have a white fill, so they pop against the panel background.

**Comment by DianaTavares** [comment]
I can see the labels on the mystery screen! I like how they look. Also, I agree with @arouinfar, the lighter gray looks good for the panels. I like the idea of:  

> I also think the Density scale on Intro and the Density table on Mystery should both have a white fill, so they pop against the panel background.
 
I also think that is better if the scale is a solid color. At this moment it has like transparency and I feel that can get a little lost:

![image](https://user-images.githubusercontent.com/26031501/77104153-29ea4b00-69e1-11ea-9359-1df1a81a39ce.png)

**Comment by arouinfar** [comment]
> I also think the Density scale on Intro and the Density table on Mystery should both have a white fill, so they pop against the panel background.

To be clear, I'm referring to these components:
![image](https://user-images.githubusercontent.com/8419308/77105054-a29dd700-69e2-11ea-944d-19f41324c9cd.png)
![image](https://user-images.githubusercontent.com/8419308/77105074-a7fb2180-69e2-11ea-8be1-d12637e4acd9.png)

**Comment by jonathanolson** [comment]
Assorted tweaks for this now in master, can you take a look?

**Comment by DianaTavares** [comment]
I like how the panels look and the color of the scale in the Mystery screen. I can't click on the scale and move it, but it can be pushed by the blocks. 
![Untitled](https://user-images.githubusercontent.com/26031501/77681963-c077b880-6f5b-11ea-96d4-f1d559ba23a7.gif)
This issue was created for the development of the Mystery screen, and now it is a mix of several mini issues. Please @jonathanolson, let me know if is better to close this issue an open a new one for the small bugs in the screen.

**Comment by arouinfar** [comment]
@jonathanolson @DianaTavares the current look in master isn't quite what I was suggesting, sorry for being unclear. I like using the light gray for the AccordionBox fill, but I was recommending that the rectangle containing Human, Glass, Titanium, etc. have a white fill. Similarly, the density table itself would have a white fill, but its AccordionBox would have a light gray fill like the other panels in the sim.

That said, I will defer to @DianaTavares since she's the lead designer.

**Comment by DianaTavares** [comment]
Oh! you mean something like this:
![image](https://user-images.githubusercontent.com/26031501/77683967-daff6100-6f5e-11ea-862d-b0401a9306ba.png)
yes, you are right the with help to read better the text, but in this way, all the panels are the same color. Agree!!

**Comment by arouinfar** [comment]
Exactly. Thanks for the mockup @DianaTavares.

**Comment by jonathanolson** [comment]
The scale should now NOT move, and I believe I fixed up the colors. I'm fine handling in this issue or separate ones, no preference. Anything else to be done here?

**Comment by arouinfar** [comment]
The colors and scale behavior is looking good to me.

**Comment by DianaTavares** [comment]
Yes, the colors and scale are perfect!
