### ISSUE TITLE
User suggestion: move the scale into the water

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/density#60]
I see in the [design doc](https://docs.google.com/document/d/1bVEDecBZwk7CTpCepDsHP6IAy_2NQDB4pPw4ubWadAA/edit#heading=h.e1du2ucs81ii) that the scale position was locked by JO on January, 30 2020. I thought I would make an issue for this comment either way, it will likely come up again if this was a widely-used feature in the Flash version.

> I have used the Density Simulation in the past. The "Mystery" tab has a scale in it. I used to be able to move the scale, including placing the scale into the water.  Now the scale can not be moved. Moving the scale allowed students to be able to calculate the buoyant force (by finding the difference in the weight on the scale on land vs. in the water.) We would compare this to calculating the buoyant force using archimedes principle.

**Comment by DianaTavares** [comment]
Calculate the buoyant force is a learning goal for Buoyancy and not for the Density sim. The scale in the Density sim is for calculating the density of the objects, and for that, the scale needs to be outside of the pool.  then my thinking is the scale with not movement in the density sim is the right decision.  @arouinfar what do you think?

**Comment by arouinfar** [comment]
I think the user is thinking of the Buoyancy sim, which has a lot of similarities to Density, though different learning goals. It doesn't look like the scale was movable in the Flash version of Density, and I agree with @DianaTavares that it doesn't serve the learning goals to move the scale underwater.

**Comment by oliver-phet** [comment]
Thanks all, replied to the user.

**Comment by oliver-phet** [comment]
Reply back from user:
> What I like about the sims is the ability to use them in the way that is best for my classes (and not only the intended use). I used the scale in this sim to calculate the apparent mass of objects in the water (when it was in the water) and the true mass when it was on land. It was great having the option of moving the scale. I don't think that making the scale "fixed" has any benefit, as allowing people to move it gives options, while not taking away the (perhaps) intended use.  
> 
> One of the benefits of the density sim over the Buoyancy Simulation is that the scale shows the mass (or apparent mass). The Buoyancy Sim shows force in Newtons. This means that we are forced to using g = 9.8 and my 9th grade physics class uses g = 10 m/s/s. Perhaps having an option for the value of g (either 9.8 or 10) would be really beneficial (I tend to use Phet sims more with my lower level classes where we use 10 and not as much with my AP classes) and it would not be too difficult to program. 
>

**Comment by oliver-phet** [comment]
Perhaps for Buoyancy we could consider an option or query parameter to toggle mass vs force scales?

**Comment by DianaTavares** [comment]
That is a good point. PhET sims are important for flexibility and the several learning goals that can cover. I am not sure if is better to add kg to the Buoyancy sim, that everything is related with forces, or allow the scale to move in Desinty. Probably a thing to discuss in the next design meeting.

**Comment by DianaTavares** [comment]
during the design meeting on July 29, 2021, it was discussed the idea of a quarry parameter to add a scale in the water. @ariel-phet  commented that is better to have fixed scales to not generate questions not related to the goal of the sim, like the change in the mass value in the scale if a student moves the scale in the sim with a block in the top.

**Comment by DianaTavares** [comment]
We discuss this in the design meeting again, and we agree that this is more suitable for Buoyancy, then better to think of a solution to this user suggestion in that simulation, for example, a query parameter that changes the lecture in the scales to kg in place of newtons.
