### ISSUE TITLE
Switching block sets leads to warning in console

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/density#61]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
Found on master on 4/27/21.
When switching the types of blocks, the console puts out a warning that the texture is being resized. It doesn't seem to lead to any error. Happens on the first screen when adding a second block, and on the third screen when switching or refreshing sets.

**Visuals**
<img width="412" alt="texture_has_been_resized" src="https://user-images.githubusercontent.com/41024075/116317163-360e1380-a770-11eb-82de-6a29621a7a2b.png">
![textureresize](https://user-images.githubusercontent.com/41024075/116317165-36a6aa00-a770-11eb-883a-9b61121b89fc.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: Density
URL: https://bayes.colorado.edu/dev/phettest/density/density_en.html?ea&brand=phet
Version: 1.0.0-dev.15 (unbuilt)
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36
Language: en-US
Window: 1280x658
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by jonathanolson** [comment]
Looking at https://stackoverflow.com/questions/55175351/remove-texture-has-been-resized-console-logs-in-three-js, I do believe this is not a concern. I don't think the resizing code will be good maintainability-wise, and we need the mipmapping. Three.js is doing this nicely right now, so I think it's best to just have the warnings print. Thanks for making the issue!
