### ISSUE TITLE
User reported issue: WebGL disabled, missing screen icons

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/density#62]
@jonathanolson I'm out of ideas on this one. They are on a up-to-date version of Chrome, but WebGL is disabled? (And I assume that is the root cause of the issues?)
The user also created a screencast of the sim behavior: https://watch.screencastify.com/v/eGlJlS0lhqmpG8dmPXsG

> **Test device** PC
> 
> **Operating System** Windows 10
> 
> **Browser** Chrome Version 90.0.4430.93 (Official Build) (64-bit)
> 
> **Problem Description** No images or activities appear
> 
> **Steps to reproduce** This only happens on our PCs it works on our Chromebooks and Laptops
> 
> **Visuals**
> ![image](https://user-images.githubusercontent.com/5090275/116916030-05aff480-ac0a-11eb-8cab-13b2a02d7e8f.png)
> 
> 
> Inspection of page
> ![image](https://user-images.githubusercontent.com/5090275/116916044-09dc1200-ac0a-11eb-95c4-5a913fe1ebcb.png)
> 
> 
> Troubleshooting information:
> !!!!! DO NOT EDIT !!!!!
> Name: ‪Density‬
> URL: http://phet.colorado.edu/sims/html/density/latest/density_en.html?fbclid=IwAR08zrLCRnCsRSw7dWyFItEhV1xWarINFCypD0xBTB9P1sI761jffJ2Mjq4
> Version: 1.0.0-dev.9 2020-05-08 14:46:54 UTC
> Features missing: applicationcache, applicationcache, touch
> User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36
> Language: en-US
> Window: 1626x838
> Pixel Ratio: 1/1
> WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
> GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
> Vendor: WebKit (WebKit WebGL)
> Vertex: attribs: 32 varying: 32 uniform: 256
> Texture: size: 8192 imageUnits: 16 (vertex: 16, combined: 32)
> Max viewport: 8192x8192
> OES_texture_float: true
> Dependencies JSON: {}

**Comment by jonathanolson** [comment]
It looks like the user has a lot of extensions enabled, what happens if those are disabled (and the browser restarted)? The console output definitely has non-standard scripts running.

**Comment by oliver-phet** [comment]
> No extensions and I'm still not able to load this simulation.
> ![image](https://user-images.githubusercontent.com/5090275/117025512-32bae080-acb8-11eb-8e96-97a319f5fa97.png)
> ![image](https://user-images.githubusercontent.com/5090275/117025549-3cdcdf00-acb8-11eb-99cc-1f13e4eb51b1.png)
> I am thinking this has to be our web filter, Securly.

I'm going to ask the user to see if they can whitelist phet.colorado.edu.

**Comment by oliver-phet** [comment]
User is investigating with Securly. Closing for now as it seems this issue is related to their web filter.

**Comment by oliver-phet** [comment]
To document, another user wrote in with the same issue (Securly).
