### ISSUE TITLE
Block labels overlap each other

### ISSUE THREAD

**Issue by stemilymill** [phetsims/density#64]
Different situation than #42.

**Test device**
Dell laptop, Chromebook

**Operating System**
Win10, Chrome OS

**Browser**
Firefox 89.0.2 , Chrome 91.0.4472.124, Chrome OS 90.0.4430.218

**Problem description**
For https://github.com/phetsims/qa/issues/663
When one or more blocks are small and placed directly next to each other, their labels overlap.

**Steps to reproduce**
Select Intro screen
Add second block
Make at least one of the blocks as small as possible
Place a small block directly to the left of the other block

**Visuals**
![labels overlap with left block small](https://user-images.githubusercontent.com/85511101/124334264-8e90d100-db64-11eb-97cf-37a1e60c9e7c.jpg)
![labels overlap with both blocks small](https://user-images.githubusercontent.com/85511101/124334266-90f32b00-db64-11eb-9d23-c599b5a05674.jpg)
![labels overlap with left block small ground edition](https://user-images.githubusercontent.com/85511101/124334320-bed86f80-db64-11eb-9f7b-f86478483696.jpg)

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Density‬
URL: https://phet-dev.colorado.edu/html/density/1.0.0-dev.16/phet/density_all_phet.html
Version: 1.0.0-dev.16 2021-06-22 15:36:28 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0
Language: en-US
Window: 1408x668
Pixel Ratio: 1.3636363636363635/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

**Comment by jonathanolson** [comment]
@DianaTavares, should I just make the labels smaller size so this isn't possible?

**Comment by DianaTavares** [comment]
No, the size of the text is nice the way it is, this issue is only visible when one of the blocks is in the smallest volume and only hides the units. The students can see what is the mass value. @arouinfar  and I agree that this is not a problem that interferes with user experience or learning. closing!

**Comment by Nancy-Salpepi** [comment]
@diana I just wanted you to know that the values can also be blocked, not just the units. 
<img width="517" alt="Screen Shot 2021-08-25 at 11 37 57 AM" src="https://user-images.githubusercontent.com/87318828/130827831-4a27fa78-b114-43f1-8717-df6648b815f4.png">
