### ISSUE TITLE
Blocks in different positions on the scale cause the scale to show different masses

### ISSUE THREAD

**Issue by stemilymill** [phetsims/density#65]
**Test device**
Dell laptop

**Operating System**
Win10

**Browser**
Chrome 91.0.4472.124
Firefox 89.0.2

**Problem description**
For https://github.com/phetsims/qa/issues/663
In the Mystery screen, a block will produce slightly different scale readings depending on the location on scale. 
For smaller blocks, this only seems to happen when almost all of the block is hanging off the side of the scale, but for large blocks it is a much more likely case to happen in student use, especially when using a trackpad input.

**Steps to reproduce**
In the Mystery screen, select the largest block and place it on the scale.
Slide the block to the left and right, releasing the block at each end.

**Visuals**

Random block set:

![mystery screen random different block position on scale causes different scale readings](https://user-images.githubusercontent.com/85511101/124655835-64922400-de6e-11eb-8dda-22bfb9c20c16.gif)
![mystery screen random different block position on scale causes different scale readings2](https://user-images.githubusercontent.com/85511101/124655698-34e31c00-de6e-11eb-985b-2024ad7ce4ad.gif)

Set 2
![mystery screen random different block position on scale causes different scale readings3 set 2](https://user-images.githubusercontent.com/85511101/124655707-390f3980-de6e-11eb-8cb8-7ce4e11b7786.gif)

Set 3

![mystery screen random different block position on scale causes different scale readings4 set 3](https://user-images.githubusercontent.com/85511101/124655882-7378d680-de6e-11eb-879b-025dd83faac3.gif)

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Density‬
URL: https://phet-dev.colorado.edu/html/density/1.0.0-dev.16/phet/density_all_phet.html
Version: 1.0.0-dev.16 2021-06-22 15:36:28 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36
Language: en-US
Window: 1418x688
Pixel Ratio: 1.3541666269302368/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true

**Comment by KatieWoe** [comment]
I noticed this while dev testing as well. It can be inconsistent sometimes. It seems like the different masses might occur if one of the masses is pushed into/overlapping the scale.

**Comment by jonathanolson** [comment]
It looks like this is based on the presence of the invisible barrier to the left. With it removed, the readings seem to become consistent.

**Comment by jonathanolson** [comment]
@stemilymill can you see if the above commit fixes this in master? I added a minor "push" on the left side of the barrier, that will overcome the friction that the scale gives it.

Turns out it's related to the block being partially overlapped with an invisible barrier, but the scale's friction keeping it from resolving.

**Comment by KatieWoe** [comment]
Looks good on master

**Comment by jonathanolson** [comment]
Thanks!
