### ISSUE TITLE
Placing block adjacent to block on scale causes scale to read 0.0 kg

### ISSUE THREAD

**Issue by stemilymill** [phetsims/density#66]
**Test device**
Dell laptop

**Operating System**
Win10

**Browser**
Firefox 89.0.2
Replicated on Chrome 91.0.4472.124

**Problem description**
For phetsims/qa#663
In Mystery screen, if one large block is on the scale and another block is placed directly beside it (touching) the scale will read 0 kg

**Steps to reproduce**
Go to Mystery screen
Place a block on the scale
Place another block against the side of the block on the scale

**Visuals**

![mystery screen set 2 placing another block against the one on the scale makes scale read 0 (2)](https://user-images.githubusercontent.com/85511101/124658073-542f7880-de71-11eb-8e37-d9aa40813885.gif)

![mystery screen set 2 placing another block against the one on the scale makes scale read 0](https://user-images.githubusercontent.com/85511101/124658114-61e4fe00-de71-11eb-92d1-e13437f339e5.gif)

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Density‬
URL: https://phet-dev.colorado.edu/html/density/1.0.0-dev.16/phet/density_all_phet.html
Version: 1.0.0-dev.16 2021-06-22 15:36:28 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36
Language: en-US
Window: 1418x688
Pixel Ratio: 1.3541666269302368/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

**Comment by stemilymill** [comment]
Also, occasionally, if the blocks are pressed together and then you let go of the block, the scale reading will glitch continuously.

![mystery screen random adjacent blocks make scale reading glitchy](https://user-images.githubusercontent.com/85511101/124658625-fc454180-de71-11eb-9f4a-90c08a99366b.gif)

**Comment by jonathanolson** [comment]
This seems again related to the combination of the barrier and friction. Looking for workarounds (I'll see if I can get rid of friction on vertical surfaces).

**Comment by jonathanolson** [comment]
I've killed all vertical-only friction with the above commit. I believe this should fix the issue. @stemilymill can you verify in master?

**Comment by DianaTavares** [comment]
I already review this and it is working perfectly. Thanks, Jonathan!!
