### ISSUE TITLE
Inconsistent shading behavior in Intro screen

### ISSUE THREAD

**Issue by stemilymill** [phetsims/density#68]
**Test device**
Dell laptop

**Operating System**
Win10

**Browser**
Chrome 91.0.4472.124

**Problem description**
For https://github.com/phetsims/qa/issues/663.  Similar to https://github.com/phetsims/density/issues/38. Probably not a big concern, since the shadow was left alone last year. When I noticed it, I was mostly wondering if there is supposed to be some object casting a shadow. @DianaTavares , do you think this needs to be fixed?

Like in #38, the shading behavior is not consistent between various materials in the Intro screen. However, the shading does not change at the horizon, but much higher up.

**Steps to reproduce**
Select Intro screen
Select wood, ice, or aluminum for the block material
Move the block toward the top of the screen

**Visuals**
![Intro screen no shadow at top](https://user-images.githubusercontent.com/85511101/124797123-ee4dfa00-df1f-11eb-9c50-3ad9b34e59c8.gif)
![Intro screen no shadow at top3](https://user-images.githubusercontent.com/85511101/124797432-3d942a80-df20-11eb-8ab9-3dfb1409d878.gif)

On Compare and Mystery screens:
![Intro screen no shadow at top2 ](https://user-images.githubusercontent.com/85511101/124797504-4f75cd80-df20-11eb-9acc-4602e3c050f5.gif)

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Density‬
URL: https://phet-dev.colorado.edu/html/density/1.0.0-dev.16/phet/density_all_phet.html
Version: 1.0.0-dev.16 2021-06-22 15:36:28 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36
Language: en-US
Window: 1418x688
Pixel Ratio: 1.3541666269302368/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

**Comment by DianaTavares** [comment]
thanks to report this strange behavior. Users need to pay a lot of attention to see this effect. I don't think is necessary for now an effort to solve this. I am going to leave it open but deferred it.

**Comment by DianaTavares** [comment]
I don't think this is a big concern. @jonathanolson, is this problem easy and fast to solve?  if the answer is not, then I think is better to move this issue to deferred or wonfix.

**Comment by jonathanolson** [comment]
@DianaTavares can you check out the shading in master? I've updated it to a different (but very similar) static environment map, that I believe should resolve this issue and look similar to the previous version (with internal simplifications).

**Comment by DianaTavares** [comment]
I like the way it is. It looks simpler, less "shiny", and I like it.
