### ISSUE TITLE
Scale's max width for text is too long

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/density#69]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Firefox
**Problem description**
For https://github.com/phetsims/qa/issues/663
The string on the scale in the third screen can go off the scale and look odd when the strings are long. I'm not certain if this is likely to actually happen.
**Steps to reproduce**
1. Use stringTest double or long
2. Go to the third screen and observe the scale

**Visuals**
<img width="217" alt="extralongscale" src="https://user-images.githubusercontent.com/41024075/124951433-96bb9700-dfd0-11eb-8dc7-fe6305698060.png">
<img width="167" alt="toolongscale" src="https://user-images.githubusercontent.com/41024075/124951437-97ecc400-dfd0-11eb-9d97-db5769a1264a.png">

**Comment by DianaTavares** [comment]
In general units and numbers are not large translations, then the most probably is that we are not going to have this type of situation with large text in the scale mass readout. 
@jonathanolson, please do the maxWidth of the text the same that the scale. Thanks!!

**Comment by jonathanolson** [comment]
@DianaTavares I've updated the maxWidth, can you see how it looks?

**Comment by DianaTavares** [comment]
Working! thanks!!
