### ISSUE TITLE
open space to move blocks out of the pool 

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/density#73]
During the first interview of Density, and also commented by @Emily2, it is difficul for the users to move blocks in the mystery screen of the sim. It has 5 blocks that require students to measure volume and mass, and some student's strategies require arranging the blocks out of the pool.  The idea, for now, is to move the invisible walls, that limit the movement of the blocks, the   scale and control panels to the extremes of the window: 
![Screen Shot 2021-07-30 at 2 51 43 p m](https://user-images.githubusercontent.com/26031501/127705645-d144abea-b640-469c-b9b9-6b79e984dd1d.png)
in that way the blocks can be moved to any place of the ground. 
When the user modifies the window to a smaller size, the corners of the window are going to push the blocks to always be visible. The same  apply for the compare screen, but not for the intro screen, where the right invisible wall stay, to don't allow the blocks to be behind the mass/volume control when the two blocks options is selected.

**Comment by jonathanolson** [comment]
Implemented. Also helpful is the new `?showBarrier` query parameter, which will visually show where the (usually invisible) barrier is, since it's now changing locations.

Can you let me know how this looks?

**Comment by DianaTavares** [comment]
The idea was to move also the scale to always be at the edge of the screen to not allow blocks to get crushed to the left of the scale when the screen change its size:

![image](https://user-images.githubusercontent.com/26031501/128276641-a063ea18-3291-4ce6-918d-0a06da67a521.png)

![image](https://user-images.githubusercontent.com/26031501/128276664-a78ddcc1-0f99-46fe-a232-10cdc6162c56.png)

**Comment by jonathanolson** [comment]
Implemented, however:

1. Load the sim in a wider aspect, Mystery screen:
![image](https://user-images.githubusercontent.com/480878/128285993-c4bb1282-ec78-4ccd-bc06-a9aa8d45d3e3.png)

2. Move the blue block:
![image](https://user-images.githubusercontent.com/480878/128286034-9fe6f54e-a6c8-4dbd-9814-959bba1af220.png)

3. Do something to instantly shift the size (e.g. opening dev-tools, command-option-I on Mac):
![image](https://user-images.githubusercontent.com/480878/128286106-db247540-30cc-4155-854b-6d5e2f6b4613.png)

**Comment by DianaTavares** [comment]
working well. If we don't lose blocks is all right.
