### ISSUE TITLE
change the values of blocks in set 1 in the mystery screen 

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/density#74]
Now that I finished with the interviews, I identify that some changes in the mystery screen, set 1, will support students to identify better:  1) how to measure the volume of the blocks (for that reason two blocks need to have the same volume, but one of them sink and other not), 2) identify the relationship of the density value with the prediction of a block sinking or floating in the water, for that reason one block need a density of 1, and 3) is better if one block behaves the same that the intro screen, then one of the materials need to be the same that the ones in the intro. 

For that reazon this are the values for the blocks (I undrstand that then leabel of the blocks is goign to be modified to better arrange the blocks in the screen by size): 

<google-sheets-html-origin><style type="text/css"></style>

  | A | B | C | D | E
-- | -- | -- | -- | -- | --
Mass | 19.32 | 0.4 | 19.32 | 5 | 2.8
Volume | 5.5 | 1 | 1 | 5 | 7
Density | 3.51 | 0.4 | 19.32 | 1 | 0.4
Material | Diamond | Wood | Gold | Water | wood

**Comment by jonathanolson** [comment]
Implemented above, can you try it out?

**Comment by DianaTavares** [comment]
I don't see the change. I already try `command-shift-R` to refresh the sim, and one of the small blocks is still being Diamond when it should be wood.  

![image](https://user-images.githubusercontent.com/26031501/128349087-6b183a97-366c-421e-bc03-dbfcaaa61024.png)

**Comment by DianaTavares** [comment]
I  see it working, thanks!!
