### ISSUE TITLE
Add sliders to the compare screen 

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/density#75]
In the last design, the meeting was discussed to include sliders bars in the compare screen to make it more interactive. The mockups are: 

For "same mass" have a slider to adjust the mass but the volumes do not change. The slider is from 1 to 10 kg. 
![image](https://user-images.githubusercontent.com/26031501/128542807-15c54f28-1972-4985-885a-a9cc5628eb7f.png)

For "same volume" have a slider to adjust the volumes but the default mass does not change
![image](https://user-images.githubusercontent.com/26031501/128542845-487d4067-f661-41f0-a322-26bb41706ced.png)

For "same density" have a slider to adjust the density. The mass will be modified, but no the volume. 
![image](https://user-images.githubusercontent.com/26031501/128544188-0defa4d8-0ee1-4660-8d23-eba3d677b25c.png)

Finally, change the order of the screens. And rename the intro to Explore. 

![image](https://user-images.githubusercontent.com/26031501/128545013-f5409e99-cc65-4bcc-adb6-5350039cf8b2.png)

**Comment by jonathanolson** [comment]
Implemented, can you verify?

Also, highly recommend we change the density range so it doesn't really go past 2. The zone from 1.01 to 10 is... functionally identical, and takes up the large majority of the slider space.

**Comment by DianaTavares** [comment]
I love it! and you are right, density doesn't need to go to 10. I think that a max value of 2 is enough.

**Comment by jonathanolson** [comment]
Implemented above.

**Comment by DianaTavares** [comment]
Nice!  The last thing related to this is that the sliders need to snap every 0.1 steps. 

Once that that is ready we are going to be ready for the second round of interviews, and a dev version is going to be needed. Thanks!

**Comment by jonathanolson** [comment]
Implemented, published https://phet-dev.colorado.edu/html/density/1.0.0-dev.18/phet/density_all_phet.html if you need it (let me know if you need another version whenever).

**Comment by DianaTavares** [comment]
Amazing, thanks!!
