### ISSUE TITLE
`comboBox.listBox` contents are missing in studio tree

### ISSUE THREAD

**Issue by arouinfar** [phetsims/density#77]
For #76 

There are four ComboBoxes in Density and they are all currently missing the listBox contents in Studio.
<img src="https://user-images.githubusercontent.com/8419308/128938288-89e8f36d-b3c9-4435-b75a-44bdcf4bf61f.png" width=200>

For an example of what a ComboBox normally looks like in Studio, see `phScale.macroScreen.view.soluteComboBox`
<img src="https://user-images.githubusercontent.com/8419308/128938155-a8273f2b-feda-48f9-b97a-42594acc7d7b.png" width=200>

**Comment by jonathanolson** [comment]
Should be fixed with the above commit, can you verify?

**Comment by arouinfar** [comment]
Looks good, thanks!
