### ISSUE TITLE
Remove properties related to displaying force vectors

### ISSUE THREAD

**Issue by arouinfar** [phetsims/density#78]
For #76 

These properties are specific to Buoyancy, and it would be best to hide/remove them from the tree. If the sim cannot remain stateful with these things removed, let's instead set them to phetioReadOnly: true.
- [x] `density.*Screen.model.showBuoyancyForceProperty`
- [x] `density.*Screen.model.showContactForceProperty`
- [x] `density.*Screen.model.showForceValuesProperty`
- [x] `density.*Screen.model.showGravityForceProperty`

**Comment by jonathanolson** [comment]
Implemented above.

**Comment by arouinfar** [comment]
👍🏻
