### ISSUE TITLE
Several properties should be phetioReadOnly: true

### ISSUE THREAD

**Issue by arouinfar** [phetsims/density#79]
For #76 

These properties should be read-only, as there is no need for the client to directly set them.

- [x] `density.*Screen.model.gravityProperty`
- [x] `density.*Screen.model.liquidMaterialProperty`
- [x] `density.*Screen.model.pool.liquidYInterpolatedProperty`
- [x] `density.*Screen.model.pool.liquidVolumeProperty`

For each block:
- [x] `buoyancyForceInterpolatedProperty`
- [x] `contactForceInterpolatedProperty`
- [x] `gravityForceInterpolatedProperty`
- [x] `sizeProperty`
- [x] `userControlledProperty`

**Comment by jonathanolson** [comment]
I believe these should all be handled with the above commit.

**Comment by arouinfar** [comment]
Looks good, thanks!
