### ISSUE TITLE
One/Two mass selection positioning

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/density#8]
It's possible to center-align the buttons with the panel (horizontally), and bottom-align them with the pool, but on the intro screen this feels way too close to the reset-all button:

<img width="303" alt="Screen Shot 2020-03-09 at 3 43 56 PM" src="https://user-images.githubusercontent.com/480878/76260221-f22f1680-621c-11ea-832a-a500969c087a.png">

Thoughts?

**Comment by arouinfar** [comment]
I like the bottom-alignment with the pool, but I think center-aligning the RadioButtonGroup with the panel above brings it too close the the ResetAllButton. In this case, I'd probably left-align the RadioButtonGroup with he panel above it.

**Comment by DianaTavares** [comment]
I agree with @arouinfar, I think is better a left alignment with the panel.

**Comment by jonathanolson** [comment]
Implemented the left alignment.

**Comment by ariel-phet** [comment]
Left alignment looks good to me on master. Closing
