### ISSUE TITLE
Change name of compare screen to intro, and modify some initial values 

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/density#82]
Now that the order of the screens is different, it is necessary to change the name of the compare screen to **intro**.

also is better to have nicer numbers in the "same density" option. The changes are: 

default density = 0.5 kg/L

red block volume = 1L, mass =0.5 kg
green block volume = 2 L, mass = 1 kg
blue block volume = 4 L, mass = 2 kg
yellow block, volume = 6 L, mass = 3 kg

**Comment by jonathanolson** [comment]
Should be implemented with the above changes, can you verify?

**Comment by DianaTavares** [comment]
it is working! Thanks!!
