### ISSUE TITLE
Add a gradient fo color to the blocks in the compare screen 

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/density#84]
Related to the last design meeting (August 19th, 2021) and the interviews with students performed, the changes for the Density sim are: 

- [x] go back to the original order and names of the screens: Intro, Compare, Mystery
- [x] In the Intro screen, have the density readout by default open 
- [x] In the compare screen, add a gradient color to the blocks associate with their density. The color of each block should get darker as the density increases (same behavior that the "custom" block in the intro screen, but maintaining the color of the block). For example, the green color can go from the lightest color in the next picture, to the darker: 

![image](https://user-images.githubusercontent.com/26031501/130503275-78854474-821c-4bad-a5bc-f45f2037a3e9.png)

**Comment by jonathanolson** [comment]
Implemented the changes above, can you verify? Also see if the gradient scales look good (they can be somewhat adjustable).

**Comment by DianaTavares** [comment]
Working perfectly. Thanks @jonathanolson
