### ISSUE TITLE
Block remains suspended when released in Studio Wrapper

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/density#85]
Test device**
Macbook Air (m1 chip)

**Operating System**
11.4

**Browser**
chrome

**Problem description**
In Studio wrapper: If block is released when mouse pointer is off screen, the block remains suspended until mouse focus returns to screen. This is seen both before and after sim is launched in studio. 

**Steps to reproduce**
In any screen in Studio Wrapper:
1. Lift a block up until the mouse focus is off screen. 
2. Release the block 

**Visuals**

https://drive.google.com/file/d/1kRkZkOf4YvPRsXBfG18jx5oKj_5DsRW2/view?usp=sharing

**Comment by jonathanolson** [comment]
This is unfortunately expected, due to Chrome's implementation of events with iframes. @arouinfar can you confirm? (This was the subject of the out-of-iframe maintenance releases).

Marking as won't-fix

**Comment by arouinfar** [comment]
Yes, that's correct @jonathanolson. This looks like https://github.com/phetsims/scenery/issues/1186, so this behavior is expected.
