### ISSUE TITLE
Scale position changes

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/density#86]
**Test device**
MacBook Air (m1 chip)

**Operating System**
11.4

**Browser**
chrome

**Problem description**
In the mystery screen, the location of the scale changes when the reset button is pressed. 

**Steps to reproduce**
1. Select the Mystery screen
2. Move a couple of blocks around
3. Press the reset button

**Visuals**
https://drive.google.com/file/d/1Ijgx0Z_djYkiVMUHcYu4IVhml7P3m_tX/view?usp=sharing

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: Density
URL: https://bayes.colorado.edu/dev/phettest/density/density_en.html?ea&brand=phet
Version: 1.0.0-dev.18 (unbuilt)
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36
Language: en-US
Window: 1440x659
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

**Comment by Nancy-Salpepi** [comment]
This is also seen in the Studio wrapper--If the Mystery Screen is not accessed until after the sim is launched, the scale will appear suspended over the pool.

**Comment by jonathanolson** [comment]
I believe the above issues should be fixed in master. Can you verify?

**Comment by Nancy-Salpepi** [comment]
@jonathanolson this looks fixed on Master in the sim, mirror wrapper and studio wrapper

**Comment by jonathanolson** [comment]
Thanks!
