### ISSUE TITLE
block can be dragged "into" scale

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/density#88]
**Test device**
Macbook Air (m1 chip)

**Operating System**
11.4. 

**Browser**
chrome

**Problem description**
On the Mystery Screen, the 1b block can be dragged "into" the scale using a denser block--such as 1c or 1a. I noticed this when I went to lift the 1c block over the 1b to get to the scale. I wasn't intentionally trying to move/ram the 1b block. 

I can also reproduce this with the 1e and 3d blocks, but the movement into the scale isn't as severe. 

**Steps to reproduce**
1. Open the mystery screen tab
2. Place the 1b block next to the scale
3. Place the 1c (or 1a) block on top of the 1b block. 
4. Drag the 1c block down and to the left. 

**Visuals**

![blockintoscale2](https://user-images.githubusercontent.com/87318828/131018258-839c1f6d-2fe1-4af2-971e-8543d2223614.gif)

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: Density
URL: https://bayes.colorado.edu/dev/phettest/density/density_en.html?ea&brand=phet
Version: 1.0.0-dev.18 (unbuilt)
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36
Language: en-US
Window: 1440x659
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

**Comment by jonathanolson** [comment]
Good find!

It looks like the block being pushed into the ground is then pushing up with a large force (to compensate), which is causing a large friction force, which gets to the point it overwhelms the collision force.

I don't offhand see a great way to tune this. @DianaTavares and @arouinfar thoughts about severity?

**Comment by DianaTavares** [comment]
it doesn't represent a big problem for student's interaction with the sim. Then we leave it open, in case users report it, but for now, the decision is not to fix it.

**Comment by arouinfar** [comment]
Since this is marked as wontfix, and Density has been published for more than a year, I'm going to close it. If users report this issue, it can be reopened and we can reassess.
