### ISSUE TITLE
`density.global.view.colorProfile` should only contain colors relevant to Density

### ISSUE THREAD

**Issue by arouinfar** [phetsims/density#89]
For #76 

Several of the colors in the color profile only apply to the Buoyancy simulation. Can they be removed from Density @jonathanolson?
<img src="https://user-images.githubusercontent.com/8419308/131278159-575cd528-6bd7-4ebf-86b2-e2f5ea059d2d.png" width=200>

**Comment by jonathanolson** [comment]
@samreid or @zepumph, could we conditionally remove the display of color properties? Or would it be best to conditionally provide opt-out tandems?

**Comment by samreid** [comment]
How about DensityColors.js and BuoyancyColors.js?

**Comment by samreid** [comment]
Would it be easy to have a list of DensityMaterials and BuoyancyMaterials, or is it better to have them all defined together?

**Comment by jonathanolson** [comment]
It would be better to have them defined together.

**Comment by zepumph** [comment]
What about metadata on them that can conditionally instrument? Or conditionally phetioFeature them depending on what sim is being run?

**Comment by zepumph** [comment]
What about using something like the namespace solution from https://github.com/phetsims/scenery/issues/1259? Or will this not work because they are all defined in the common repo?

**Comment by zepumph** [comment]
Probably it will be best to just have a ternary on how you provide the Tandem, like for 

https://github.com/phetsims/density-buoyancy-common/blob/6703af36f2c598358f2bdbbaa3def94d5198bfbd/js/common/view/DensityBuoyancyCommonColors.js#L110

. . . .

```js
    tandem: DENSITY_IS_THE_SIM ? tandem.createTandem( 'mysteryOrangeColorProperty' ) : Tandem.OPT_OUT
```

**Comment by jonathanolson** [comment]
It looks like the ternary is working best. Committed above, @arouinfar can you verify?

**Comment by arouinfar** [comment]
Thanks @jonathanolson! The tree looks much better now.
