### ISSUE TITLE
Delete temp production deploy

### ISSUE THREAD

**Issue by mattpen** [phetsims/density#9]
Per request from @kathy-phet, there was a temporary dev version deployed to the production location. This must be removed from phet-server before version 1.0 is deployed with the build server.

It can be removed by running the following on phet-server:

`rm -rf /data/web/static/phetsims/sims/html/density`

Contact me if there are any questions.

**Comment by jonathanolson** [comment]
Presumably it can be removed. @mattpen is this safe to do now?

**Comment by mattpen** [comment]
@jonathanolson - it should have been removed before publication, unless there was some other reason to keep it around I'm not aware of. I'll remove it now. It can be restored from peta if needed.
