### ISSUE TITLE
Each `numberControl.slider` should contain a linked property 

### ISSUE THREAD

**Issue by arouinfar** [phetsims/density#90]
For #76 

All sliders should contain a linked property that points to the corresponding property. 

For example, `density.introScreen.model.densityProperty` should appear under `density.introScreen.view.densityNumberControl.slider` as a linked property.

**Comment by jonathanolson** [comment]
I believe this should be complete. Almost all of those cases are unit changes or things like density-to-material, those are ok to link? Can you verify?
