### ISSUE TITLE
Instrument Blocks panels

### ISSUE THREAD

**Issue by arouinfar** [phetsims/density#94]
For #76 

The Blocks panels on the Intro and Mystery screens should be instrumented so that the panel can be completely hidden when the user wants to hide the RadioButtonGroup.
![image](https://user-images.githubusercontent.com/8419308/132066720-3a73e76f-2d12-49d5-8e02-8edbfce11d21.png)
![image](https://user-images.githubusercontent.com/8419308/132066725-2e642bdb-3165-4fc0-a0a7-bc2c35dd786a.png)

@jonathanolson please make the following changes:
- [x]  Instrument these panels as `density.*Screen.view.blocksPanel`
- [x]  Each panel should have a top-level `visibleProperty`
- [x]  The RadioButtonGroup should be a child of `blocksPanel`.

**Comment by jonathanolson** [comment]
Implemented above, can you verify?

**Comment by arouinfar** [comment]
Looks good, thanks @jonathanolson
