### ISSUE TITLE
Rename `modeRadioButtonGroup` to `blocksRadioButtonGroup`

### ISSUE THREAD

**Issue by arouinfar** [phetsims/density#95]
For #76 

These RadioButtonGroups in the Blocks panels are currently `modeRadioButtonGroup` and the underlying property is `model.modeProperty`. 
![image](https://user-images.githubusercontent.com/8419308/132066720-3a73e76f-2d12-49d5-8e02-8edbfce11d21.png)
![image](https://user-images.githubusercontent.com/8419308/132066725-2e642bdb-3165-4fc0-a0a7-bc2c35dd786a.png)

"Mode" is a bit ambiguous, and the tree would be a bit cleaner if we could instead use `blocksRadioButtonGroup`. This also follows a pattern of {{title}}RadioButtonGroup (where {{title}} is the string used in the sim's view) that we usually see in other sims.

@jonathanolson please make these changes:
- [x] Rename `modeRadioButtonGroup` to `blocksRadioButtonGroup`
- [x] Rename `model.modeProperty` to `model.blockSetProperty`
- [x] Rename `modeRefreshButton` to `randomBlocksRefreshButton` since it only applies to the random block set.

**Comment by jonathanolson** [comment]
Implemented above (and a ton of code renaming too), can you verify?

**Comment by arouinfar** [comment]
Looks great, thanks @jonathanolson
