### ISSUE TITLE
Create derived property `scaleMeasuredMassProperty`

### ISSUE THREAD

**Issue by arouinfar** [phetsims/density#97]
For #76 

In Density, the scale readout displays the mass in kg. Clients may want this information in the data stream. It can be derived from `model.scale.scaleForceInterpolatedProperty`, but it would be more convenient if we could do the calculation for them.

@jonathanolson please create `model.scale.scaleMeasuredMassProperty` with units of kg and make it read-only.

**Comment by jonathanolson** [comment]
Implemented above, can you verify?

**Comment by arouinfar** [comment]
Looks good, thanks!
