### ISSUE TITLE
PhET-iO Client Guides

### ISSUE THREAD

**Issue by arouinfar** [phetsims/density#99]
This sim will need PhET-iO client guides before going into rc testing. I sent a Slack message to @kathy-phet to ask if there are any client-specific requests.

**Comment by arouinfar** [comment]
@jonathanolson I tagged this a blocks publication, but it only blocks RC versions, not dev versions.

**Comment by arouinfar** [comment]
I added and edited the client guides in the above commits. @jonathanolson I am a bit unsure of the wording in this request https://github.com/phetsims/phet-io-client-guides/blob/master/density/client-requests.md#set-the-initial-position-and-properties-of-the-blocks. Can you please review the language?

**Comment by jonathanolson** [comment]
Looks good to me!

**Comment by arouinfar** [comment]
Thanks for the review @jonathanolson. Closing.
